window.lessonConfig = {
  lesson:9, topic:"Prime & Composite Numbers", storageKey:"harry-thinkacademy-lesson9-v2",
  titleHtml:"Think first.<br><em>Check the pattern.</em>",
  description:"Practice all thirteen original missed groups and one closely matched group with new numbers.",
  recordDate:"Aug 15, 2026", recordNumbers:"1–13",
  groups:[
    {number:"1",original:{prompt:"Which list contains only prime numbers?",fields:[{id:"o01",type:"choice",options:[{key:"A",text:"39, 31, 71, 29"},{key:"B",text:"23, 37, 43, 17"},{key:"C",text:"18, 65, 1, 47"},{key:"D",text:"2, 9, 11, 29"}],answer:"B"}]},similar:{prompt:"Which new list contains only prime numbers?",fields:[{id:"s01",type:"choice",options:[{key:"A",text:"17, 19, 23, 29"},{key:"B",text:"13, 21, 31, 41"},{key:"C",text:"2, 7, 15, 37"},{key:"D",text:"11, 25, 43, 47"}],answer:"A"}]}},
    {number:"2",original:{prompt:"Calculate each original answer.",fields:[{id:"o02a",expression:"12 × 10 =",answer:120},{id:"o02b",expression:"21 × 10 =",answer:210},{id:"o02c",expression:"10 × 15 =",answer:150},{id:"o02d",expression:"40 × 19 =",answer:760},{id:"o02e",expression:"76 × 20 =",answer:1520},{id:"o02f",expression:"50 × 37 =",answer:1850}]},similar:{prompt:"Calculate each similar answer.",fields:[{id:"s02a",expression:"14 × 10 =",answer:140},{id:"s02b",expression:"23 × 10 =",answer:230},{id:"s02c",expression:"10 × 17 =",answer:170},{id:"s02d",expression:"30 × 18 =",answer:540},{id:"s02e",expression:"64 × 20 =",answer:1280},{id:"s02f",expression:"50 × 29 =",answer:1450}]}},
    {number:"3",original:{prompt:"Find the space-station code.",note:"It is between 40 and 70. Its ones digit is 3 less than its tens digit. It is prime.",fields:[{id:"o03",label:"Code",answer:41}]},similar:{prompt:"Find the new space-station code.",note:"It is between 20 and 50. Its ones digit is 2 less than its tens digit. It is prime.",fields:[{id:"s03",label:"Code",answer:31}]}},
    {number:"4",original:{prompt:"What describes the set {2, 13, 53, 67, 89, …}?",fields:[{id:"o04",type:"choice",options:[{key:"A",text:"All odd numbers"},{key:"B",text:"All even numbers"},{key:"C",text:"All prime numbers"},{key:"D",text:"All composite numbers"}],answer:"C"}]},similar:{prompt:"What describes the set {11, 19, 31, 47, 73, …}?",fields:[{id:"s04",type:"choice",options:[{key:"A",text:"All odd numbers"},{key:"B",text:"All even numbers"},{key:"C",text:"All prime numbers"},{key:"D",text:"All composite numbers"}],answer:"C"}]}},
    {number:"5",original:{prompt:"Fill in the missing prime numbers.",fields:[{id:"o05a",expression:"41, 43, __, 53, 59",answer:47},{id:"o05b",expression:"59, __, 67, 71, 73, 79",answer:61}]},similar:{prompt:"Fill in the new missing prime numbers.",fields:[{id:"s05a",expression:"11, 13, __, 19, 23",answer:17},{id:"s05b",expression:"23, __, 31, 37, 41, 43",answer:29}]}},
    {number:"6",original:{prompt:"Classify each number.",fields:[{id:"o06a",type:"choice",options:[{key:"A",text:"9 is prime"},{key:"B",text:"9 is composite"}],answer:"B"},{id:"o06b",type:"choice",options:[{key:"A",text:"17 is prime"},{key:"B",text:"17 is composite"}],answer:"A"}]},similar:{prompt:"Classify each new number.",fields:[{id:"s06a",type:"choice",options:[{key:"A",text:"15 is prime"},{key:"B",text:"15 is composite"}],answer:"B"},{id:"s06b",type:"choice",options:[{key:"A",text:"19 is prime"},{key:"B",text:"19 is composite"}],answer:"A"}]}},
    {number:"7",original:{prompt:"Among 83, 71, 69, 58, 72, and 49, how many are prime and composite?",fields:[{id:"o07a",label:"Prime numbers",answer:2},{id:"o07b",label:"Composite numbers",answer:4}]},similar:{prompt:"Among 97, 73, 87, 64, 81, and 55, how many are prime and composite?",fields:[{id:"s07a",label:"Prime numbers",answer:2},{id:"s07b",label:"Composite numbers",answer:4}]}},
    {number:"8",original:{prompt:"Find the area of each original shaded figure.",note:"Each small square has area 1.",figure:{type:"image",src:"./assets/question-08.png",alt:"Two shaded figures on square grids.",caption:"Count full squares; join partial pieces when helpful."},fields:[{id:"o08a",label:"Figure 1 area",answer:15},{id:"o08b",label:"Figure 2 area",answer:11}]},similar:{prompt:"Find the area of each new shaded figure.",figure:{type:"cellPair",boards:[{rows:3,cols:5,on:[0,1,2,3,5,6,7,8,10,11,12,13]},{rows:3,cols:4,on:[0,1,2,4,5,6,7,8,9,10]}]},fields:[{id:"s08a",label:"Figure 1 area",answer:12},{id:"s08b",label:"Figure 2 area",answer:10}]}},
    {number:"9",original:{prompt:"Find all the factors of 14.",fields:[{id:"o09",type:"choice",options:[{key:"A",text:"1, 14"},{key:"B",text:"2, 7"},{key:"C",text:"1, 2, 7, 14, 28"},{key:"D",text:"1, 2, 7, 14"}],answer:"D"}]},similar:{prompt:"Find all the factors of 18.",fields:[{id:"s09",type:"choice",options:[{key:"A",text:"1, 18"},{key:"B",text:"2, 3, 6, 9"},{key:"C",text:"1, 2, 3, 6, 9, 18"},{key:"D",text:"1, 2, 3, 6, 9, 18, 36"}],answer:"C"}]}},
    {number:"10",original:{prompt:"Classify 12.",fields:[{id:"o10",type:"choice",options:[{key:"A",text:"Prime"},{key:"B",text:"Composite"}],answer:"B"}]},similar:{prompt:"Classify 19.",fields:[{id:"s10",type:"choice",options:[{key:"A",text:"Prime"},{key:"B",text:"Composite"}],answer:"A"}]}},
    {number:"11",original:{prompt:"Which row of a 1–100 number chart has only one prime number?",note:"Row 1 is 1–10, row 2 is 11–20, and so on.",fields:[{id:"o11",type:"choice",options:[{key:"A",text:"1st row"},{key:"B",text:"6th row"},{key:"C",text:"9th row"},{key:"D",text:"10th row"}],answer:"D"}]},similar:{prompt:"Which row of a 1–100 number chart has three prime numbers?",note:"Row 1 is 1–10, row 2 is 11–20, and so on.",fields:[{id:"s11",type:"choice",options:[{key:"A",text:"2nd row"},{key:"B",text:"4th row"},{key:"C",text:"5th row"},{key:"D",text:"6th row"}],answer:"C"}]}},
    {number:"12",original:{prompt:"Find the prime number.",fields:[{id:"o12",type:"choice",options:[{key:"A",text:"24"},{key:"B",text:"16"},{key:"C",text:"41"},{key:"D",text:"64"}],answer:"C"}]},similar:{prompt:"Find the composite number.",fields:[{id:"s12",type:"choice",options:[{key:"A",text:"37"},{key:"B",text:"53"},{key:"C",text:"57"},{key:"D",text:"71"}],answer:"C"}]}},
    {number:"13",original:{prompt:"Which pair has both a prime and a composite number?",fields:[{id:"o13",type:"choice",options:[{key:"A",text:"4 and 7"},{key:"B",text:"3 and 13"},{key:"C",text:"14 and 28"},{key:"D",text:"6 and 8"}],answer:"A"}]},similar:{prompt:"Which pair has one prime and one composite number?",fields:[{id:"s13",type:"choice",options:[{key:"A",text:"5 and 12"},{key:"B",text:"7 and 19"},{key:"C",text:"8 and 14"},{key:"D",text:"9 and 21"}],answer:"A"}]}}
  ]
};
