window.lessonConfig = {
  lesson:11, topic:"Basic Coordinate Plane", storageKey:"harry-thinkacademy-lesson11-v2",
  titleHtml:"Plot it.<br><em>Then calculate.</em>",
  description:"Redo each missed Lesson 11 question, then solve one closely matched question with new points or numbers.",
  recordDate:"Aug 30, 2026", recordNumbers:"2, 4, 8, 9, 10, 11, 12, 13",
  groups:[
    {number:"2",original:{prompt:"Find the point that matches each ordered pair.",note:"Remember: move across for x, then move up for y.",figure:{type:"image",src:"./assets/question-02.png",alt:"A coordinate plane with points G, H, I, J, K, L, M, and N.",caption:"Use the ordered pair (x, y) to locate each point."},fields:[
      {id:"o02a",type:"choice",expression:"Point (3, 8):",options:[{key:"A",text:"G"},{key:"B",text:"H"},{key:"C",text:"L"},{key:"D",text:"J"}],answer:"B"},
      {id:"o02b",type:"choice",expression:"Point (9, 1):",options:[{key:"A",text:"M"},{key:"B",text:"N"},{key:"C",text:"K"},{key:"D",text:"I"}],answer:"C"}
    ]},similar:{prompt:"Find the point that matches each new ordered pair.",note:"Across first, then up.",figure:{type:"coordinatePlane",points:[{label:"A",x:2,y:7},{label:"B",x:6,y:4},{label:"C",x:8,y:2},{label:"D",x:4,y:9}]},fields:[
      {id:"s02a",type:"choice",expression:"Point (2, 7):",options:[{key:"A",text:"A"},{key:"B",text:"B"},{key:"C",text:"C"},{key:"D",text:"D"}],answer:"A"},
      {id:"s02b",type:"choice",expression:"Point (8, 2):",options:[{key:"A",text:"A"},{key:"B",text:"B"},{key:"C",text:"C"},{key:"D",text:"D"}],answer:"C"}
    ]}},
    {number:"4",original:{prompt:"Buildings are at (4, 12) and (4, 5). How many grid squares apart are they?",note:"The x-coordinates match, so compare the y-coordinates.",figure:{type:"coordinatePlane",maxX:6,maxY:12,connect:true,points:[{label:"A",x:4,y:12},{label:"B",x:4,y:5}]},fields:[{id:"o04",label:"Distance in grid squares",answer:7}]},similar:{prompt:"Buildings are at (7, 13) and (7, 4). How many grid squares apart are they?",note:"The points are on the same vertical line.",figure:{type:"coordinatePlane",maxX:9,maxY:13,connect:true,points:[{label:"C",x:7,y:13},{label:"D",x:7,y:4}]},fields:[{id:"s04",label:"Distance in grid squares",answer:9}]}},
    {number:"8",original:{prompt:"A rectangular playground has corners at (3, 1), (3, 7), (7, 1), and (7, 7). Each grid unit is 10 meters. How far is one lap around it?",note:"Find the rectangle’s perimeter in grid units, then multiply by 10.",figure:{type:"coordinatePlane",connect:true,points:[{label:"A",x:3,y:1},{label:"B",x:3,y:7},{label:"D",x:7,y:7},{label:"C",x:7,y:1}]},fields:[{id:"o08",label:"Meters",answer:200}]},similar:{prompt:"A rectangular playground has corners at (2, 2), (2, 8), (7, 2), and (7, 8). Each grid unit is 8 meters. How far is one lap around it?",note:"Find both side lengths before finding the perimeter.",figure:{type:"coordinatePlane",connect:true,points:[{label:"E",x:2,y:2},{label:"F",x:2,y:8},{label:"H",x:7,y:8},{label:"G",x:7,y:2}]},fields:[{id:"s08",label:"Meters",answer:176}]}},
    {number:"9",original:{prompt:"A square flower bed has corners at (1, 3), (1, 7), (5, 7), and (5, 3). Each grid unit is 5 meters. How much fencing is needed?",note:"Find one side, then multiply by 4 and by 5 meters.",figure:{type:"coordinatePlane",connect:true,points:[{label:"A",x:1,y:3},{label:"B",x:1,y:7},{label:"C",x:5,y:7},{label:"D",x:5,y:3}]},fields:[{id:"o09",label:"Meters of fencing",answer:80}]},similar:{prompt:"A square garden has corners at (2, 2), (2, 8), (8, 8), and (8, 2). Each grid unit is 4 meters. How much fencing is needed?",note:"All four sides of a square have equal length.",figure:{type:"coordinatePlane",connect:true,points:[{label:"E",x:2,y:2},{label:"F",x:2,y:8},{label:"G",x:8,y:8},{label:"H",x:8,y:2}]},fields:[{id:"s09",label:"Meters of fencing",answer:96}]}},
    {number:"10",original:{prompt:"Calculate. Write every answer in simplest form.",note:"For unlike denominators, make equal-size fraction pieces first.",fields:[
      {id:"o10a",type:"text",expression:"2/5 + 1/5 =",answer:"3/5"},{id:"o10b",type:"text",expression:"7/8 − 3/8 =",answer:"1/2"},{id:"o10c",type:"text",expression:"3/6 − 2/6 =",answer:"1/6"},
      {id:"o10d",type:"text",expression:"2/7 + 1/4 =",answer:"15/28"},{id:"o10e",type:"text",expression:"2/3 + 1/9 =",answer:"7/9"},{id:"o10f",type:"text",expression:"3/8 + 1/4 =",answer:"5/8"},
      {id:"o10g",type:"text",expression:"1/2 − 1/4 =",answer:"1/4"},{id:"o10h",type:"text",expression:"5/6 − 4/5 =",answer:"1/30"},{id:"o10i",type:"text",expression:"7/9 − 1/3 =",answer:"4/9"}
    ]},similar:{prompt:"Calculate the similar set. Write every answer in simplest form.",note:"Simplify each result before checking it.",fields:[
      {id:"s10a",type:"text",expression:"3/7 + 2/7 =",answer:"5/7"},{id:"s10b",type:"text",expression:"7/10 − 3/10 =",answer:"2/5"},{id:"s10c",type:"text",expression:"5/8 − 1/8 =",answer:"1/2"},
      {id:"s10d",type:"text",expression:"1/3 + 1/5 =",answer:"8/15"},{id:"s10e",type:"text",expression:"3/4 + 1/8 =",answer:"7/8"},{id:"s10f",type:"text",expression:"1/6 + 1/3 =",answer:"1/2"},
      {id:"s10g",type:"text",expression:"3/5 − 1/10 =",answer:"1/2"},{id:"s10h",type:"text",expression:"7/8 − 2/3 =",answer:"5/24"},{id:"s10i",type:"text",expression:"5/6 − 1/2 =",answer:"1/3"}
    ]}},
    {number:"11",original:{prompt:"Calculate using long multiplication.",note:"Line up the ones place before multiplying.",fields:[{id:"o11a",expression:"25 × 4 =",answer:100},{id:"o11b",expression:"125 × 8 =",answer:1000,answerLabel:"1,000"}]},similar:{prompt:"Calculate the new problems using long multiplication.",fields:[{id:"s11a",expression:"36 × 5 =",answer:180},{id:"s11b",expression:"115 × 6 =",answer:690}]}},
    {number:"12",original:{prompt:"Calculate with round numbers.",note:"Multiply the non-zero digits, then use place value.",fields:[{id:"o12a",expression:"8 × 1,000 =",answer:8000,answerLabel:"8,000"},{id:"o12b",expression:"14 × 100 =",answer:1400,answerLabel:"1,400"}]},similar:{prompt:"Calculate the similar round-number problems.",fields:[{id:"s12a",expression:"7 × 1,000 =",answer:7000,answerLabel:"7,000"},{id:"s12b",expression:"16 × 100 =",answer:1600,answerLabel:"1,600"}]}},
    {number:"13",original:{prompt:"Calculate with round numbers.",note:"Keep the value of every place.",fields:[{id:"o13a",expression:"62 × 100 =",answer:6200,answerLabel:"6,200"},{id:"o13b",expression:"109 × 10 =",answer:1090,answerLabel:"1,090"}]},similar:{prompt:"Calculate the similar round-number problems.",fields:[{id:"s13a",expression:"48 × 100 =",answer:4800,answerLabel:"4,800"},{id:"s13b",expression:"107 × 10 =",answer:1070,answerLabel:"1,070"}]}}
  ]
};
