window.lessonConfig = {
  lesson:8, topic:"Solid Figures & Factors", storageKey:"harry-thinkacademy-lesson8-v2",
  titleHtml:"See it.<br><em>Solve it.</em>",
  description:"Redo every missed Lesson 8 question, then use the same idea on a new similar question.",
  recordDate:"Aug 8, 2026", recordNumbers:"1–8",
  groups:[
    {number:"1",original:{prompt:"Which statement about this rectangular prism is TRUE?",figure:{type:"solid",kind:"box",alt:"A rectangular prism."},fields:[{id:"o01",type:"choice",options:[{key:"A",text:"It is a prism."},{key:"B",text:"The lateral faces are triangles."},{key:"C",text:"It has 8 faces."},{key:"D",text:"Each base has 12 edges."}],answer:"A"}]},similar:{prompt:"Which statement about this cube is TRUE?",figure:{type:"solid",kind:"cube",alt:"A cube."},fields:[{id:"s01",type:"choice",options:[{key:"A",text:"It is a prism."},{key:"B",text:"The lateral faces are triangles."},{key:"C",text:"It has 8 faces."},{key:"D",text:"Each base has 12 edges."}],answer:"A"}]}},
    {number:"2",original:{prompt:"Which statements about this triangular prism are FALSE? Choose all that apply.",figure:{type:"solid",kind:"tri-prism",alt:"A triangular prism."},fields:[{id:"o02",type:"multi",options:[{key:"A",text:"It has 2 bases."},{key:"B",text:"The lateral faces are triangles."},{key:"C",text:"It has 9 edges."},{key:"D",text:"The bases have 9 vertices."}],answer:["B","D"],answerLabel:"B and D"}]},similar:{prompt:"Which statements about this pentagonal prism are FALSE? Choose all that apply.",figure:{type:"solid",kind:"pent-prism",alt:"A pentagonal prism."},fields:[{id:"s02",type:"multi",options:[{key:"A",text:"It has 2 bases."},{key:"B",text:"The lateral faces are triangles."},{key:"C",text:"It has 15 edges."},{key:"D",text:"The bases have 15 vertices."}],answer:["B","D"],answerLabel:"B and D"}]}},
    {number:"3",original:{prompt:"Which list shows all the factors of 9?",fields:[{id:"o03",type:"choice",options:[{key:"A",text:"3"},{key:"B",text:"1, 3, 9"},{key:"C",text:"3, 9"},{key:"D",text:"3, 9, 27"}],answer:"B"}]},similar:{prompt:"Which list shows all the factors of 10?",fields:[{id:"s03",type:"choice",options:[{key:"A",text:"1, 10"},{key:"B",text:"2, 5, 10"},{key:"C",text:"1, 2, 5, 10"},{key:"D",text:"1, 2, 5, 10, 20"}],answer:"C"}]}},
    {number:"4",original:{prompt:"Calculate each original answer.",fields:[
      {id:"o04a",expression:"410 + 254 =",answer:664},{id:"o04b",expression:"42 + 134 =",answer:176},{id:"o04c",expression:"33 + 76 =",answer:109},
      {id:"o04d",expression:"220 − 54 =",answer:166},{id:"o04e",expression:"78 + 430 =",answer:508},{id:"o04f",expression:"41 + 523 =",answer:564},
      {id:"o04g",expression:"310 − 239 =",answer:71},{id:"o04h",expression:"723 − 11 =",answer:712},{id:"o04i",expression:"42 + 24 =",answer:66}
    ]},similar:{prompt:"Calculate each similar answer.",fields:[
      {id:"s04a",expression:"420 + 253 =",answer:673},{id:"s04b",expression:"43 + 125 =",answer:168},{id:"s04c",expression:"34 + 78 =",answer:112},
      {id:"s04d",expression:"230 − 56 =",answer:174},{id:"s04e",expression:"79 + 420 =",answer:499},{id:"s04f",expression:"42 + 514 =",answer:556},
      {id:"s04g",expression:"320 − 248 =",answer:72},{id:"s04h",expression:"734 − 12 =",answer:722},{id:"s04i",expression:"43 + 25 =",answer:68}
    ]}},
    {number:"5",original:{prompt:"Which list shows all the factors of 12?",fields:[{id:"o05",type:"choice",options:[{key:"A",text:"1, 12"},{key:"B",text:"2, 3, 4, 6"},{key:"C",text:"1, 2, 3, 4, 6, 12"},{key:"D",text:"12, 24, 36"}],answer:"C"}]},similar:{prompt:"Which list shows all the factors of 18?",fields:[{id:"s05",type:"choice",options:[{key:"A",text:"1, 18"},{key:"B",text:"1, 2, 3, 6, 9, 18"},{key:"C",text:"2, 3, 6, 9, 18"},{key:"D",text:"1, 2, 3, 6, 9, 18, 36"}],answer:"B"}]}},
    {number:"6",original:{prompt:"Four equal cubes make this cuboid. Its total edge length is 72 inches. How long is one cube edge?",figure:{type:"cubeRow",count:4,label:"4 equal cubes",alt:"Four equal cubes joined in a row."},fields:[{id:"o06",label:"One cube edge in inches",answer:3}]},similar:{prompt:"Five equal cubes make this cuboid. Its total edge length is 112 inches. How long is one cube edge?",figure:{type:"cubeRow",count:5,label:"5 equal cubes",alt:"Five equal cubes joined in a row."},fields:[{id:"s06",label:"One cube edge in inches",answer:4}]}},
    {number:"7",original:{prompt:"What is the name of this solid figure?",figure:{type:"solid",kind:"cylinder",alt:"A cylinder."},fields:[{id:"o07",type:"choice",options:[{key:"A",text:"Sphere"},{key:"B",text:"Cylinder"},{key:"C",text:"Pyramid"},{key:"D",text:"Circle"}],answer:"B"}]},similar:{prompt:"What is the name of this solid figure?",figure:{type:"solid",kind:"sphere",alt:"A sphere."},fields:[{id:"s07",type:"choice",options:[{key:"A",text:"Sphere"},{key:"B",text:"Cylinder"},{key:"C",text:"Pyramid"},{key:"D",text:"Circle"}],answer:"A"}]}},
    {number:"8",original:{prompt:"What is the name of this solid figure?",figure:{type:"solid",kind:"box",alt:"A rectangular prism."},fields:[{id:"o08",type:"choice",options:[{key:"A",text:"Rectangle"},{key:"B",text:"Square"},{key:"C",text:"Rectangular Prism"},{key:"D",text:"Cube"}],answer:"C"}]},similar:{prompt:"What is the name of this solid figure?",figure:{type:"solid",kind:"cube",alt:"A cube."},fields:[{id:"s08",type:"choice",options:[{key:"A",text:"Rectangle"},{key:"B",text:"Square"},{key:"C",text:"Rectangular Prism"},{key:"D",text:"Cube"}],answer:"D"}]}}
  ]
};
