const fraction = (top, bottom) =>
  `<span class="math-fraction" aria-label="${top} over ${bottom}"><span>${top}</span><span>${bottom}</span></span>`;

window.STAR_MATH_TESTS = [
  {
    id: "2026-08-09",
    dateLabel: "August 9, 2026",
    shortDate: "Aug 9",
    extractedLabel: "Recorded and extracted August 9, 2026",
    questions: [
      {
        id: "2026-08-09-q1",
        number: 1,
        skill: "Mean (average)",
        promptHtml: "What is the mean of the following numbers?<div class=\"star-equation\">15, 10, 7, 12</div>",
        choicesHtml: ["15", "11", "10", "12"],
        correctIndex: 1,
        explanation: "Add the numbers to get 44, then divide by the 4 numbers. 44 ÷ 4 = 11.",
      },
      {
        id: "2026-08-09-q2",
        number: 2,
        skill: "Lines, rays, and line segments",
        promptHtml: "Identify a line segment.",
        choicesHtml: ["ray SQ", "segment ST", "line TR", "ray PR"],
        correctIndex: 1,
        explanation: "A line segment has two endpoints and no arrowheads. ST is the segment.",
        visual: "geometry",
      },
      {
        id: "2026-08-09-q3",
        number: 3,
        skill: "Decimal place value",
        promptHtml: "In what place is the digit 3 in the number <strong>427.53</strong>?",
        choicesHtml: ["tens", "tenths", "hundreds", "hundredths"],
        correctIndex: 3,
        explanation: "The 3 is the second digit to the right of the decimal point, so it is in the hundredths place.",
      },
      {
        id: "2026-08-09-q4",
        number: 4,
        skill: "Elapsed time",
        promptHtml: "The clocks show two times in the same morning. How much time has passed?",
        choicesHtml: ["3 minutes", "10 minutes", "8 minutes", "18 minutes"],
        correctIndex: 2,
        explanation: "The start time is 8:25 and the end time is 8:33. Eight minutes have passed.",
        visual: "clocks",
      },
      {
        id: "2026-08-09-q5",
        number: 5,
        skill: "Input-output rules",
        promptHtml: "Which rule can be used to find the output numbers in this table?",
        choicesHtml: [
          "Multiply the input number by 6.",
          "Subtract the input number from 72.",
          "Divide the input number by 6.",
          "Multiply the input number by 4.",
        ],
        correctIndex: 0,
        explanation: "Every output is 6 times its input: 2 × 6 = 12, 6 × 6 = 36, and 12 × 6 = 72.",
        visual: "input-output",
      },
      {
        id: "2026-08-09-q11",
        number: 11,
        skill: "Adding fractions",
        promptHtml: `<div class="star-equation">${fraction(1, 6)} + ${fraction(4, 6)} = ?</div>`,
        choicesHtml: [fraction(5, 12), fraction(4, 12), fraction(4, 6), fraction(5, 6)],
        correctIndex: 3,
        explanation: "The denominators are the same. Add 1 + 4 and keep the denominator 6, giving 5/6.",
      },
      {
        id: "2026-08-09-q14",
        number: 14,
        skill: "Equivalent fractions",
        promptHtml: `<div class="star-equation">${fraction(5, 2)} = ${fraction("?", 6)}</div>`,
        choicesHtml: ["10", "20", "15", "12"],
        correctIndex: 2,
        explanation: "The denominator 2 is multiplied by 3 to make 6, so multiply 5 by 3 too. The missing numerator is 15.",
      },
      {
        id: "2026-08-09-q17",
        number: 17,
        skill: "Estimating quotients",
        promptHtml: "Estimate:<div class=\"star-equation\">55 ÷ 6</div>",
        choicesHtml: ["9", "50", "8", "40"],
        correctIndex: 0,
        explanation: "Use the nearby compatible number 54. Since 54 ÷ 6 = 9, the best estimate is 9.",
      },
      {
        id: "2026-08-09-q18",
        number: 18,
        skill: "Distributive property",
        promptHtml: "Which expression has the same value as <strong>1,695 × 6</strong>?",
        choicesHtml: [
          "(1 × 6) + (6 × 6) + (9 × 6) + (5 × 6)",
          "(1,000 × 6) + (600 × 6) + (9 × 6) + (5 × 6)",
          "(1,000 × 6) + (600 × 6) + (90 × 6) + (5 × 6)",
          "(1 × 6) + (600 × 6) + (90 × 6) + (5 × 6)",
        ],
        correctIndex: 2,
        explanation: "Break 1,695 into 1,000 + 600 + 90 + 5, then multiply every part by 6.",
      },
      {
        id: "2026-08-09-q19",
        number: 19,
        skill: "Rounding whole numbers",
        promptHtml: "What is <strong>95,705</strong> rounded to the thousands place?",
        choicesHtml: ["95,700", "95,000", "96,000", "95,800"],
        correctIndex: 2,
        explanation: "The hundreds digit is 7, so round the thousands place up. 95,705 rounds to 96,000.",
      },
      {
        id: "2026-08-09-q21",
        number: 21,
        skill: "Decimals on a number line",
        promptHtml: "What number is closest to the value of Q on the number line?",
        choicesHtml: ["3.03", "0.3", "3.8", "3.3"],
        correctIndex: 3,
        explanation: "Q is between 3 and 4 and about three tenths past 3, so its value is about 3.3.",
        visual: "number-line",
      },
      {
        id: "2026-08-09-q23",
        number: 23,
        skill: "Perimeter",
        promptHtml: "What is the perimeter of the rectangle?",
        choicesHtml: ["1,740 feet", "170 feet", "85 feet", "1,750 feet"],
        correctIndex: 1,
        explanation: "Add all four sides: 50 + 35 + 50 + 35 = 170 feet.",
        visual: "rectangle",
      },
      {
        id: "2026-08-09-q24",
        number: 24,
        skill: "Two-step word problem",
        promptHtml: "There are 15 students in a classroom with 6 tables. If 2 students can sit at a table, how many students <strong>cannot</strong> sit down at tables?",
        choicesHtml: ["6", "15", "3", "2"],
        correctIndex: 2,
        explanation: "Six tables seat 12 students. Then 15 − 12 = 3 students without seats.",
      },
      {
        id: "2026-08-09-q25",
        number: 25,
        skill: "Multiplying three factors",
        promptHtml: "Multiply:<div class=\"star-equation\">4 × 15 × 6</div>",
        choicesHtml: ["84", "1,440", "360", "3,600"],
        correctIndex: 2,
        explanation: "First 4 × 15 = 60. Then 60 × 6 = 360.",
      },
      {
        id: "2026-08-09-q28",
        number: 28,
        skill: "Naming decimals",
        promptHtml: "<div class=\"star-equation\">0.914 = ?</div>",
        choicesHtml: [
          "nine hundred fourteen ten-thousandths",
          "nine hundred forty-one ten-thousandths",
          "nine hundred fourteen thousandths",
          "nine hundred forty-one thousandths",
        ],
        correctIndex: 2,
        explanation: "There are three digits after the decimal point, so 0.914 is nine hundred fourteen thousandths.",
      },
    ],
  },
  {
    id: "2026-08-16",
    dateLabel: "August 16, 2026",
    shortDate: "Aug 16",
    extractedLabel: "Recorded and extracted August 16, 2026",
    questions: [
      {
        id: "2026-08-16-q5",
        number: 5,
        skill: "Choose a reasonable metric unit",
        promptHtml: "The height of an apple would be about _____.",
        choicesHtml: ["7 kilometers", "7 meters", "7 millimeters", "7 centimeters"],
        correctIndex: 3,
        explanation: "An apple is only several centimeters tall. Seven centimeters is the reasonable measurement.",
      },
      {
        id: "2026-08-16-q7",
        number: 7,
        skill: "Add several whole numbers",
        promptHtml: "Add.",
        choicesHtml: ["4,067", "4,867", "4,967", "5,065"],
        correctIndex: 2,
        explanation: "4,185 + 36 + 28 + 718 = 4,967.",
        visual: "vertical-addition",
      },
      {
        id: "2026-08-16-q18",
        number: 18,
        skill: "Find the greatest common factor",
        promptHtml: "What is the greatest common factor of <strong>15</strong> and <strong>35</strong>?",
        choicesHtml: ["5", "30", "15", "35"],
        correctIndex: 0,
        explanation: "The common factors are 1 and 5. The greatest common factor is 5.",
      },
      {
        id: "2026-08-16-q22",
        number: 22,
        skill: "Interpret a division remainder",
        promptHtml: "There are 902 buttons on a table. A worker attaches the buttons to cards so they can be sold. Each card has 4 buttons. How many buttons does the worker leave on the table?",
        choicesHtml: ["0", "1", "2", "3"],
        correctIndex: 2,
        explanation: "902 ÷ 4 = 225 remainder 2, so 2 buttons are left on the table.",
      },
      {
        id: "2026-08-16-q23",
        number: 23,
        skill: "Estimate with money",
        promptHtml: "Miki bought some erasers for $0.39. After paying, she had $0.13 left. Which amount is a reasonable estimate of the money Miki had to start with?",
        choicesHtml: ["$0.90", "$0.50", "$0.70", "$0.30"],
        correctIndex: 1,
        explanation: "$0.39 + $0.13 = $0.52, which is reasonably estimated as $0.50.",
      },
      {
        id: "2026-08-16-q25",
        number: 25,
        skill: "Solve a multi-step rate problem",
        promptHtml: "Mrs. King has 4 bundles of wood. Each bundle has 9 pieces. The fire burns 6 pieces each hour. She keeps the fire burning until the wood is gone. How long does the fire last?",
        choicesHtml: ["10 hours", "8 hours", "6 hours", "4 hours"],
        correctIndex: 2,
        explanation: "There are 4 × 9 = 36 pieces. At 6 pieces per hour, 36 ÷ 6 = 6 hours.",
      },
      {
        id: "2026-08-16-q31",
        number: 31,
        skill: "Divide a unit fraction by a whole number",
        promptHtml: "Find the quotient.",
        choicesHtml: [fraction(1, 18), fraction(5, 4), fraction(1, 80), fraction(5, 8)],
        correctIndex: 2,
        explanation: "Dividing 1/8 into 10 equal parts gives 1/(8 × 10), or 1/80.",
        visual: "unit-fraction-division",
      },
      {
        id: "2026-08-16-q34",
        number: 34,
        skill: "Write a number in expanded form",
        promptHtml: "Which expression is another way to write <strong>29,625</strong>?",
        choicesHtml: [
          "2 × 10,000 + 9 × 1,000 + 6 × 10 + 2 × 10 + 5",
          "2 × 10,000 + 9 × 100 + 6 × 100 + 2 × 10 + 5",
          "2 × 1,000 + 9 × 1,000 + 6 × 100 + 2 × 10 + 5",
          "2 × 10,000 + 9 × 1,000 + 6 × 100 + 2 × 10 + 5",
        ],
        correctIndex: 3,
        explanation: "29,625 has 2 ten-thousands, 9 thousands, 6 hundreds, 2 tens, and 5 ones.",
      },
    ],
  },
  {
    id: "2026-08-23",
    dateLabel: "August 23, 2026",
    shortDate: "Aug 23",
    extractedLabel: "Recorded and extracted August 23, 2026",
    questions: [
      {
        id: "2026-08-23-q4",
        number: 4,
        skill: "Solve a multiplication-and-addition problem",
        promptHtml: "A disc jockey has 277 albums with 14 songs on each album and 177 singles with 1 song each. How many total songs does the disc jockey have?",
        choicesHtml: ["3,701", "2,755", "6,356", "4,055"],
        correctIndex: 3,
        explanation: "277 × 14 = 3,878. Then add 177 singles: 3,878 + 177 = 4,055 songs.",
      },
      {
        id: "2026-08-23-q13",
        number: 13,
        skill: "Multiply decimals",
        promptHtml: "Multiply.",
        choicesHtml: ["11.7", "0.097", "1.17", "0.117"],
        correctIndex: 3,
        explanation: "39 × 3 = 117. The factors have three decimal places altogether, so the product is 0.117.",
        visual: "decimal-multiplication",
      },
      {
        id: "2026-08-23-q22",
        number: 22,
        skill: "Match a decimal to an equivalent fraction",
        promptHtml: "Which fraction is equal to <strong>0.2</strong>?",
        choicesHtml: [fraction(4, 5), fraction(1, 4), fraction(80, 100), fraction(1, 5)],
        correctIndex: 3,
        explanation: "0.2 means two tenths. 2/10 simplifies to 1/5.",
      },
      {
        id: "2026-08-23-q25",
        number: 25,
        skill: "Divide a mixed number by a unit fraction",
        promptHtml: "A home builder uses the land shown for each house and has the total land shown. How many houses can she build?",
        choicesHtml: ["10", "1", "11", "13"],
        correctIndex: 2,
        explanation: "Each house uses 1/2 acre. There are eleven halves in 5 1/2, so she can build 11 houses.",
        visual: "land",
      },
      {
        id: "2026-08-23-q27",
        number: 27,
        skill: "Find a radius from a diameter",
        promptHtml: "The diameter of a circle is 22 millimeters. What is its radius?",
        choicesHtml: ["44 mm", "12 mm", "41 mm", "11 mm"],
        correctIndex: 3,
        explanation: "The radius is half the diameter. 22 ÷ 2 = 11 millimeters.",
        visual: "circle",
      },
      {
        id: "2026-08-23-q29",
        number: 29,
        skill: "Find a missing numerator in equivalent fractions",
        promptHtml: "Find the missing numerator.",
        choicesHtml: ["7", "360", "72", "77"],
        correctIndex: 3,
        explanation: "The denominator 5 is multiplied by 7 to make 35, so multiply 11 by 7 too. The numerator is 77.",
        visual: "equivalent-fraction",
      },
      {
        id: "2026-08-23-q31",
        number: 31,
        skill: "Identify decimal place value",
        promptHtml: "In what place is the digit 4 in the number <strong>712.49</strong>?",
        choicesHtml: ["tens", "hundreds", "hundredths", "tenths"],
        correctIndex: 3,
        explanation: "The 4 is the first digit to the right of the decimal point, so it is in the tenths place.",
      },
    ],
  },
  {
    id: "2026-08-30",
    dateLabel: "August 30, 2026",
    shortDate: "Aug 30",
    extractedLabel: "Recorded and extracted August 30, 2026",
    questions: [
      {
        id: "2026-08-30-q2",
        number: 2,
        skill: "Find an equivalent ratio",
        promptHtml: "A fruit drink uses a pineapple-to-cranberry ratio of <strong>14:12</strong>. Which ratio is equivalent to 14:12?",
        choicesHtml: ["7:6", "27:24", "49:48", "36:32"],
        correctIndex: 0,
        explanation: "Divide both parts of 14:12 by 2. The equivalent ratio is 7:6.",
      },
      {
        id: "2026-08-30-q5",
        number: 5,
        skill: "Convert gallons to quarts",
        promptHtml: "<div class=\"star-equation\">3 gallons = ___ quarts</div>",
        choicesHtml: ["12", "24", "2", "6"],
        correctIndex: 0,
        explanation: "One gallon equals 4 quarts, so 3 × 4 = 12 quarts.",
      },
      {
        id: "2026-08-30-q7",
        number: 7,
        skill: "Subtract multi-digit whole numbers",
        promptHtml: "Subtract.",
        choicesHtml: ["678,846", "677,846", "677,856", "682,154"],
        correctIndex: 1,
        explanation: "696,410 − 18,564 = 677,846.",
        visual: "aug30-subtraction",
      },
      {
        id: "2026-08-30-q15",
        number: 15,
        skill: "Find an average rate",
        promptHtml: "During one season, Robert played in 15 games and scored 90 points. How many points per game did he score on average that season?",
        choicesHtml: ["5 points per game", "9 points per game", "6 points per game", "4 points per game"],
        correctIndex: 2,
        explanation: "Divide the total points by the number of games: 90 ÷ 15 = 6 points per game.",
      },
      {
        id: "2026-08-30-q16",
        number: 16,
        skill: "Identify decimal place value",
        promptHtml: "In what place is the digit <strong>7</strong> in the number <strong>413.79</strong>?",
        choicesHtml: ["hundreds", "hundredths", "tens", "tenths"],
        correctIndex: 3,
        explanation: "The 7 is the first digit to the right of the decimal point, so it is in the tenths place.",
      },
      {
        id: "2026-08-30-q18",
        number: 18,
        skill: "Estimate a mixed-number sum",
        promptHtml: `Estimate:<div class="star-equation">8 ${fraction(3, 5)} + 3 ${fraction(4, 9)} = ?</div>`,
        choicesHtml: ["1", "10", "12", "8"],
        correctIndex: 2,
        explanation: "Round 8 3/5 to 9 and 3 4/9 to 3. Then 9 + 3 = 12.",
      },
      {
        id: "2026-08-30-q21",
        number: 21,
        skill: "Find a difference from a data table",
        promptHtml: "The table shows the average weight of several animals. How much greater is the weight of a moose than the weight of a polar bear?",
        choicesHtml: ["280 kg", "300 kg", "290 kg", "390 kg"],
        correctIndex: 2,
        explanation: "Subtract the polar bear's weight from the moose's weight: 700 − 410 = 290 kg.",
        visual: "aug30-animal-table",
      },
      {
        id: "2026-08-30-q23",
        number: 23,
        skill: "Divide with a remainder",
        promptHtml: "Divide.<div class=\"star-equation\">85 ÷ 6</div>",
        choicesHtml: ["12 R1", "13 R5", "15 R5", "14 R1"],
        correctIndex: 3,
        explanation: "6 × 14 = 84, and 85 − 84 = 1. The quotient is 14 R1.",
      },
      {
        id: "2026-08-30-q24",
        number: 24,
        skill: "Round to the greatest place",
        promptHtml: "What is <strong>485,783</strong> rounded to its greatest place?",
        choicesHtml: ["486,000", "490,000", "500,000", "400,000"],
        correctIndex: 2,
        explanation: "The greatest place is the hundred-thousands place. The next digit is 8, so 485,783 rounds up to 500,000.",
      },
      {
        id: "2026-08-30-q26",
        number: 26,
        skill: "Read and combine pictograph data",
        promptHtml: "The pictograph shows how many children play each sport. How many children play softball or basketball?",
        choicesHtml: ["12 children", "14 children", "6 children", "7 children"],
        correctIndex: 1,
        explanation: "Softball has 6 symbols, or 12 children. Basketball has 1 symbol, or 2 children. Altogether, 12 + 2 = 14 children.",
        visual: "aug30-pictograph",
      },
      {
        id: "2026-08-30-q27",
        number: 27,
        skill: "Estimate a shaded fraction",
        promptHtml: "About what fraction of the shape is shaded?",
        choicesHtml: [fraction(5, 8), fraction(1, 2), fraction(1, 4), fraction(5, 6)],
        correctIndex: 3,
        explanation: "Only a small part at the top is unshaded, so about 5/6 of the cylinder is shaded.",
        visual: "aug30-shaded-cylinder",
      },
      {
        id: "2026-08-30-q28",
        number: 28,
        skill: "Choose a division equation for equal groups",
        promptHtml: "Grace is playing a game with her friends. Each player gets 5 pieces. There are 45 pieces in all. Which number sentence finds the number of people playing?",
        choicesHtml: ["45 − 5 = □", "45 ÷ 5 = □", "45 × 5 = □", "45 + 5 = □"],
        correctIndex: 1,
        explanation: "The 45 pieces are split into equal groups of 5, so use 45 ÷ 5 = 9.",
      },
      {
        id: "2026-08-30-q29",
        number: 29,
        skill: "Multiply a decimal by a whole number",
        promptHtml: "Anika buys 8 juice boxes. Each juice box contains 7.5 ounces of juice. How much juice did Anika buy?",
        choicesHtml: ["96 oz", "60 oz", "9.6 oz", "15.5 oz"],
        correctIndex: 1,
        explanation: "Multiply 8 × 7.5. Eight groups of 7.5 equal 60 ounces.",
      },
      {
        id: "2026-08-30-q30",
        number: 30,
        skill: "Convert feet to inches",
        promptHtml: "<div class=\"star-equation\">5 feet = ___ inches</div>",
        choicesHtml: ["15", "61", "50", "60"],
        correctIndex: 3,
        explanation: "One foot equals 12 inches, so 5 × 12 = 60 inches.",
      },
      {
        id: "2026-08-30-q32",
        number: 32,
        skill: "Use order of operations",
        promptHtml: "What is the value of <strong>15 − 2 × 7</strong>?",
        choicesHtml: ["6", "1", "20", "91"],
        correctIndex: 1,
        explanation: "Multiply first: 2 × 7 = 14. Then subtract: 15 − 14 = 1.",
      },
      {
        id: "2026-08-30-q33",
        number: 33,
        skill: "Write a whole number in word form",
        promptHtml: "<div class=\"star-equation\">517,645,388 = ?</div>",
        choicesHtml: [
          "five hundred seventeen thousand, six hundred forty-five thousand, three hundred eighty-eight",
          "five hundred seventeen million, six hundred forty-three thousand five hundred, three hundred eighty-eight",
          "five hundred seventeen million, six hundred forty-five thousand, three hundred eighty-eight",
          "five hundred seventeen million, six hundred forty-five thousand, two hundred eight",
        ],
        correctIndex: 2,
        explanation: "Read the number in three-digit periods: 517 million, 645 thousand, and 388.",
      },
      {
        id: "2026-08-30-q34",
        number: 34,
        skill: "Find the volume of a rectangular prism",
        promptHtml: "What is the volume of the rectangular prism? Each small cube is 1 cubic inch.",
        choicesHtml: ["32 cubic inches", "10 cubic inches", "64 cubic inches", "30 cubic inches"],
        correctIndex: 0,
        explanation: "The prism is 2 cubes wide, 4 cubes high, and 4 cubes deep. Its volume is 2 × 4 × 4 = 32 cubic inches.",
        visual: "aug30-prism",
      },
    ],
  },
];

window.STAR_MATH_SIMILAR = {
  "2026-08-09-q1": {
    promptHtml: "What is the mean of the following numbers?<div class=\"star-equation\">18, 12, 9, 13</div>",
    choicesHtml: ["14", "13", "12", "15"], correctIndex: 1,
    explanation: "Add the numbers to get 52, then divide by 4. 52 ÷ 4 = 13.",
  },
  "2026-08-09-q2": {
    promptHtml: "Identify a ray.",
    choicesHtml: ["ray SQ", "segment ST", "line TR", "ray PR"], correctIndex: 0,
    explanation: "A ray has one endpoint and continues in one direction. SQ is the ray.", visual: "geometry-similar",
  },
  "2026-08-09-q3": {
    promptHtml: "In what place is the digit 4 in the number <strong>615.48</strong>?",
    choicesHtml: ["tens", "tenths", "hundreds", "hundredths"], correctIndex: 1,
    explanation: "The 4 is the first digit to the right of the decimal point, so it is in the tenths place.",
  },
  "2026-08-09-q4": {
    promptHtml: "The clocks show two times in the same morning. How much time has passed?",
    choicesHtml: ["7 minutes", "17 minutes", "27 minutes", "37 minutes"], correctIndex: 1,
    explanation: "From 9:10 to 9:27 is 17 minutes.", visual: "clocks-similar",
  },
  "2026-08-09-q5": {
    promptHtml: "Which rule can be used to find the output numbers in this table?",
    choicesHtml: ["Multiply the input number by 5.", "Add 7 to the input number.", "Multiply the input number by 7.", "Divide the input number by 7."], correctIndex: 2,
    explanation: "Every output is 7 times its input.", visual: "input-output-similar",
  },
  "2026-08-09-q11": {
    promptHtml: `<div class="star-equation">${fraction(2, 7)} + ${fraction(3, 7)} = ?</div>`,
    choicesHtml: [fraction(5, 14), fraction(5, 7), fraction(6, 7), fraction(3, 7)], correctIndex: 1,
    explanation: "The denominators match, so add 2 + 3 and keep the denominator 7. The answer is 5/7.",
  },
  "2026-08-09-q14": {
    promptHtml: `<div class="star-equation">${fraction(3, 4)} = ${fraction("?", 12)}</div>`,
    choicesHtml: ["6", "8", "9", "16"], correctIndex: 2,
    explanation: "The denominator 4 is multiplied by 3 to make 12, so multiply 3 by 3. The missing numerator is 9.",
  },
  "2026-08-09-q17": {
    promptHtml: "Estimate:<div class=\"star-equation\">71 ÷ 8</div>",
    choicesHtml: ["9", "8", "7", "10"], correctIndex: 0,
    explanation: "Use the nearby compatible number 72. Since 72 ÷ 8 = 9, the best estimate is 9.",
  },
  "2026-08-09-q18": {
    promptHtml: "Which expression has the same value as <strong>2,483 × 4</strong>?",
    choicesHtml: ["(2,000 × 4) + (400 × 4) + (80 × 4) + (3 × 4)", "(2 × 4) + (400 × 4) + (80 × 4) + (3 × 4)", "(2,000 × 4) + (40 × 4) + (8 × 4) + (3 × 4)", "(2,000 × 4) + (400 × 4) + (8 × 4) + (3 × 4)"], correctIndex: 0,
    explanation: "Break 2,483 into 2,000 + 400 + 80 + 3, then multiply every part by 4.",
  },
  "2026-08-09-q19": {
    promptHtml: "What is <strong>47,652</strong> rounded to the thousands place?",
    choicesHtml: ["47,000", "47,700", "48,000", "50,000"], correctIndex: 2,
    explanation: "The hundreds digit is 6, so round 47,000 up to 48,000.",
  },
  "2026-08-09-q21": {
    promptHtml: "What number is closest to the value of P on the number line?",
    choicesHtml: ["2.06", "0.6", "2.8", "2.6"], correctIndex: 3,
    explanation: "P is six tenths past 2, so its value is about 2.6.", visual: "number-line-similar",
  },
  "2026-08-09-q23": {
    promptHtml: "What is the perimeter of the rectangle?",
    choicesHtml: ["70 feet", "140 feet", "1,176 feet", "84 feet"], correctIndex: 1,
    explanation: "Add all four sides: 42 + 28 + 42 + 28 = 140 feet.", visual: "rectangle-similar",
  },
  "2026-08-09-q24": {
    promptHtml: "There are 19 students in a classroom with 4 tables. If 4 students can sit at a table, how many students <strong>cannot</strong> sit down at tables?",
    choicesHtml: ["3", "4", "15", "16"], correctIndex: 0,
    explanation: "Four tables seat 16 students, and 19 − 16 = 3 students cannot sit at the tables.",
  },
  "2026-08-09-q25": {
    promptHtml: "Multiply:<div class=\"star-equation\">3 × 14 × 5</div>",
    choicesHtml: ["42", "70", "210", "2,100"], correctIndex: 2,
    explanation: "First 3 × 14 = 42, then 42 × 5 = 210.",
  },
  "2026-08-09-q28": {
    promptHtml: "<div class=\"star-equation\">0.627 = ?</div>",
    choicesHtml: ["six hundred twenty-seven hundredths", "six hundred seventy-two thousandths", "six hundred twenty-seven thousandths", "six thousand twenty-seven thousandths"], correctIndex: 2,
    explanation: "There are three digits after the decimal point, so 0.627 is six hundred twenty-seven thousandths.",
  },

  "2026-08-16-q5": {
    promptHtml: "The length of a pencil would be about _____.",
    choicesHtml: ["18 kilometers", "18 meters", "18 centimeters", "18 millimeters"], correctIndex: 2,
    explanation: "A pencil is a small everyday object, so 18 centimeters is a reasonable length.",
  },
  "2026-08-16-q7": {
    promptHtml: "Add.",
    choicesHtml: ["4,104", "4,204", "4,294", "4,304"], correctIndex: 1,
    explanation: "3,642 + 57 + 89 + 416 = 4,204.", visual: "vertical-addition-similar",
  },
  "2026-08-16-q18": {
    promptHtml: "What is the greatest common factor of <strong>18</strong> and <strong>42</strong>?",
    choicesHtml: ["3", "6", "9", "12"], correctIndex: 1,
    explanation: "The greatest number that divides both 18 and 42 is 6.",
  },
  "2026-08-16-q22": {
    promptHtml: "There are 757 stickers. A teacher packs them in groups of 5. How many stickers are left after making all the complete groups?",
    choicesHtml: ["0", "1", "2", "3"], correctIndex: 2,
    explanation: "757 = 5 × 151 + 2, so 2 stickers are left.",
  },
  "2026-08-16-q23": {
    promptHtml: "Nora buys an eraser for $0.47 and has $0.16 left. Which amount is a reasonable estimate of the money she had to start with?",
    choicesHtml: ["$0.30", "$0.60", "$0.80", "$1.00"], correctIndex: 1,
    explanation: "$0.47 + $0.16 = $0.63, which is reasonably estimated as $0.60.",
  },
  "2026-08-16-q25": {
    promptHtml: "A fire has 5 bundles of wood with 8 pieces in each bundle. It burns 5 pieces each hour. How many hours will the wood last?",
    choicesHtml: ["6 hours", "7 hours", "8 hours", "10 hours"], correctIndex: 2,
    explanation: "There are 5 × 8 = 40 pieces. Then 40 ÷ 5 = 8 hours.",
  },
  "2026-08-16-q31": {
    promptHtml: "Find the quotient.",
    choicesHtml: [fraction(1, 10), fraction(1, 24), fraction(4, 6), fraction(2, 3)], correctIndex: 1,
    explanation: "Dividing 1/6 into 4 equal parts gives 1/(6 × 4), or 1/24.", visual: "unit-fraction-division-similar",
  },
  "2026-08-16-q34": {
    promptHtml: "Which expression is another way to write <strong>47,308</strong>?",
    choicesHtml: ["4 × 10,000 + 7 × 1,000 + 3 × 100 + 8", "4 × 10,000 + 7 × 100 + 3 × 10 + 8", "4 × 1,000 + 7 × 1,000 + 3 × 100 + 8", "4 × 10,000 + 7 × 1,000 + 3 × 10 + 8"], correctIndex: 0,
    explanation: "47,308 has 4 ten-thousands, 7 thousands, 3 hundreds, 0 tens, and 8 ones.",
  },

  "2026-08-23-q4": {
    promptHtml: "A disc jockey has 164 albums with 12 songs on each album and 136 singles with 1 song each. How many total songs does the disc jockey have?",
    choicesHtml: ["1,968", "2,104", "2,300", "3,320"], correctIndex: 1,
    explanation: "164 × 12 = 1,968. Then add 136 singles: 1,968 + 136 = 2,104 songs.",
  },
  "2026-08-23-q13": {
    promptHtml: "Multiply.",
    choicesHtml: ["9.6", "0.96", "0.096", "0.0096"], correctIndex: 2,
    explanation: "48 × 2 = 96. The factors have three decimal places altogether, so the product is 0.096.", visual: "decimal-multiplication-similar",
  },
  "2026-08-23-q22": {
    promptHtml: "Which fraction is equal to <strong>0.6</strong>?",
    choicesHtml: [fraction(3, 5), fraction(1, 6), fraction(2, 5), fraction(3, 4)], correctIndex: 0,
    explanation: "0.6 means six tenths. 6/10 simplifies to 3/5.",
  },
  "2026-08-23-q25": {
    promptHtml: "A home builder uses the land shown for each house and has the total land shown. How many houses can she build?",
    choicesHtml: ["6", "8", "9", "12"], correctIndex: 1,
    explanation: "Each house uses 3/4 acre. Six acres contains eight groups of 3/4, so she can build 8 houses.", visual: "land-similar",
  },
  "2026-08-23-q27": {
    promptHtml: "The diameter of a circle is 34 centimeters. What is its radius?",
    choicesHtml: ["8.5 cm", "17 cm", "34 cm", "68 cm"], correctIndex: 1,
    explanation: "The radius is half the diameter. 34 ÷ 2 = 17 centimeters.", visual: "circle-similar",
  },
  "2026-08-23-q29": {
    promptHtml: "Find the missing numerator.",
    choicesHtml: ["11", "28", "35", "80"], correctIndex: 2,
    explanation: "The denominator 4 is multiplied by 5 to make 20, so multiply 7 by 5. The missing numerator is 35.", visual: "equivalent-fraction-similar",
  },
  "2026-08-23-q31": {
    promptHtml: "In what place is the digit 6 in the number <strong>305.067</strong>?",
    choicesHtml: ["ones", "tenths", "hundredths", "thousandths"], correctIndex: 2,
    explanation: "The 6 is the second digit to the right of the decimal point, so it is in the hundredths place.",
  },

  "2026-08-30-q2": {
    promptHtml: "A trail mix uses a raisin-to-nut ratio of <strong>18:15</strong>. Which ratio is equivalent to 18:15?",
    choicesHtml: ["3:2", "6:5", "12:11", "36:15"], correctIndex: 1,
    explanation: "Divide both parts of 18:15 by 3. The equivalent ratio is 6:5.",
  },
  "2026-08-30-q5": {
    promptHtml: "<div class=\"star-equation\">5 gallons = ___ quarts</div>",
    choicesHtml: ["9", "10", "20", "25"], correctIndex: 2,
    explanation: "One gallon equals 4 quarts, so 5 × 4 = 20 quarts.",
  },
  "2026-08-30-q7": {
    promptHtml: "Subtract.",
    choicesHtml: ["557,842", "556,852", "556,842", "547,842"], correctIndex: 2,
    explanation: "584,300 − 27,458 = 556,842.", visual: "aug30-subtraction-similar",
  },
  "2026-08-30-q15": {
    promptHtml: "During one season, Elena played in 12 games and scored 96 points. How many points per game did she score on average?",
    choicesHtml: ["7 points per game", "8 points per game", "9 points per game", "12 points per game"], correctIndex: 1,
    explanation: "Divide the total points by the number of games: 96 ÷ 12 = 8 points per game.",
  },
  "2026-08-30-q16": {
    promptHtml: "In what place is the digit <strong>6</strong> in the number <strong>582.064</strong>?",
    choicesHtml: ["tenths", "thousandths", "hundredths", "ones"], correctIndex: 2,
    explanation: "The 6 is the second digit to the right of the decimal point, so it is in the hundredths place.",
  },
  "2026-08-30-q18": {
    promptHtml: `Estimate:<div class="star-equation">6 ${fraction(7, 8)} + 4 ${fraction(2, 5)} = ?</div>`,
    choicesHtml: ["9", "10", "11", "12"], correctIndex: 2,
    explanation: "Round 6 7/8 to 7 and 4 2/5 to 4. Then 7 + 4 = 11.",
  },
  "2026-08-30-q21": {
    promptHtml: "The table shows the average weight of several animals. How much greater is the weight of an elk than the weight of a black bear?",
    choicesHtml: ["355 kg", "365 kg", "375 kg", "425 kg"], correctIndex: 1,
    explanation: "Subtract the black bear's weight from the elk's weight: 725 − 360 = 365 kg.", visual: "aug30-animal-table-similar",
  },
  "2026-08-30-q23": {
    promptHtml: "Divide.<div class=\"star-equation\">97 ÷ 8</div>",
    choicesHtml: ["11 R1", "12 R1", "12 R7", "13 R1"], correctIndex: 1,
    explanation: "8 × 12 = 96, and 97 − 96 = 1. The quotient is 12 R1.",
  },
  "2026-08-30-q24": {
    promptHtml: "What is <strong>742,680</strong> rounded to its greatest place?",
    choicesHtml: ["700,000", "740,000", "743,000", "800,000"], correctIndex: 0,
    explanation: "The greatest place is the hundred-thousands place. The next digit is 4, so round down to 700,000.",
  },
  "2026-08-30-q26": {
    promptHtml: "The pictograph shows how many children joined each club. How many children joined art or music?",
    choicesHtml: ["8 children", "10 children", "12 children", "14 children"], correctIndex: 1,
    explanation: "Art has 2 symbols, or 4 children. Music has 3 symbols, or 6 children. Altogether, 4 + 6 = 10 children.", visual: "aug30-pictograph-similar",
  },
  "2026-08-30-q27": {
    promptHtml: "About what fraction of the shape is shaded?",
    choicesHtml: [fraction(1, 4), fraction(1, 2), fraction(3, 4), fraction(5, 6)], correctIndex: 2,
    explanation: "About one fourth is unshaded, so about three fourths of the cylinder is shaded.", visual: "aug30-shaded-cylinder-similar",
  },
  "2026-08-30-q28": {
    promptHtml: "A teacher shares 56 cards equally. Each student gets 7 cards. Which number sentence finds the number of students?",
    choicesHtml: ["56 − 7 = □", "56 ÷ 7 = □", "56 × 7 = □", "56 + 7 = □"], correctIndex: 1,
    explanation: "The 56 cards are split into equal groups of 7, so use 56 ÷ 7 = 8.",
  },
  "2026-08-30-q29": {
    promptHtml: "Mateo buys 6 bottles. Each bottle contains 4.5 ounces of juice. How much juice did Mateo buy?",
    choicesHtml: ["10.5 oz", "24 oz", "27 oz", "45 oz"], correctIndex: 2,
    explanation: "Multiply 6 × 4.5. Six groups of 4.5 equal 27 ounces.",
  },
  "2026-08-30-q30": {
    promptHtml: "<div class=\"star-equation\">7 feet = ___ inches</div>",
    choicesHtml: ["72", "79", "84", "96"], correctIndex: 2,
    explanation: "One foot equals 12 inches, so 7 × 12 = 84 inches.",
  },
  "2026-08-30-q32": {
    promptHtml: "What is the value of <strong>24 − 3 × 6</strong>?",
    choicesHtml: ["6", "18", "21", "126"], correctIndex: 0,
    explanation: "Multiply first: 3 × 6 = 18. Then subtract: 24 − 18 = 6.",
  },
  "2026-08-30-q33": {
    promptHtml: "<div class=\"star-equation\">804,302,019 = ?</div>",
    choicesHtml: [
      "eight hundred four thousand, three hundred two thousand, nineteen",
      "eight hundred four million, three hundred two thousand, nineteen",
      "eight hundred forty million, three hundred two thousand, nineteen",
      "eight hundred four million, thirty-two thousand, nineteen",
    ], correctIndex: 1,
    explanation: "Read the number in three-digit periods: 804 million, 302 thousand, and 19.",
  },
  "2026-08-30-q34": {
    promptHtml: "What is the volume of the rectangular prism? Each small cube is 1 cubic inch.",
    choicesHtml: ["24 cubic inches", "30 cubic inches", "36 cubic inches", "40 cubic inches"], correctIndex: 2,
    explanation: "The prism is 3 cubes wide, 3 cubes high, and 4 cubes deep. Its volume is 3 × 3 × 4 = 36 cubic inches.", visual: "aug30-prism-similar",
  },
};
