(function(root){
  'use strict';
  const qc=['The quantity in Column A is greater.','The quantity in Column B is greater.','The two quantities are equal.','The relationship cannot be determined from the information given.'];
  const q=(section,number,skill,prompt,choices,correct,tip,explanation,extra={})=>({source:(section==='VR'?1000:2000)+number,section,number,skill,prompt,choices,correct,tip,explanation,...extra});
  const vr=(n,skill,prompt,choices,c,tip,why,extra)=>q('VR',n,skill,prompt,choices,c,tip,why,extra);
  const qr=(n,skill,prompt,choices,c,tip,why,extra)=>q('QR',n,skill,prompt,choices,c,tip,why,extra);
  const originals=[
    vr(8,'Precise verb meanings','ASSAULT:',['adjourn','atone','confront','dictate'],2,'Put the word into a sentence: “They assaulted the enemy.” Think attack, not stop.','Assault means attack. Confront is the closest choice, although it is less forceful. Adjourn means end or pause a meeting; atone means make amends; dictate means give orders.',{chosen:0,seconds:4}),
    vr(9,'Multiple meanings','OBSCURE:',['desired','incomprehensible','rapt','uncovered'],1,'Obscure can mean unclear or little-known. Test the choices against those meanings.','Incomprehensible means difficult or impossible to understand, the closest choice here. Rapt means deeply absorbed or fascinated, not unclear.',{chosen:2,seconds:5}),
    vr(10,'Opposite-word traps','DISCLOSE:',['conceal','determine','protect','reveal'],3,'Use the phrase “disclose a secret.” Does the information become known or hidden?','To disclose is to reveal or make known. Conceal means hide—the opposite. Do not guess the whole word from “close” inside it.',{chosen:0,seconds:4}),
    vr(11,'Word families and roles','ORATOR:',['ambassador','comedian','guardian','lecturer'],3,'Connect oral, oration, and orator with speaking.','An orator is a public speaker; lecturer is the closest option. An ambassador represents a country. An ambassador may speak, but speaking is not the meaning of ambassador.',{chosen:0,seconds:3}),
    vr(12,'Quantity and degree','PALTRY:',['assured','meager','parasitic','tragic'],1,'A “paltry amount” is too little. Predict “small” before reading the choices.','Paltry means very small or inadequate; meager has the same meaning. Assured means confident or certain.',{chosen:0,seconds:4}),
    vr(17,'Multiple meanings','CONVICTION:',['creed','hatred','secrecy','villain'],0,'A conviction can be a firm belief, not only a court judgment.','Creed means a belief or system of beliefs. Conviction here means a firmly held belief. Hatred is a strong negative feeling, not a belief. Conviction is a noun; the source solution incorrectly labels it an adjective.',{chosen:1,seconds:62}),
    vr(18,'Useful word parts','EMBOLDEN:',['entitle','hearten','nominate','perforate'],1,'Find BOLD inside emBOLDen: make someone braver.','Hearten means encourage or give courage. Entitle means give a right or permission; that is not the same as giving confidence.',{chosen:0,seconds:2}),
    vr(31,'Category clues','The Girl Scouts of the United States of America is an organization devoted to teaching girls compassion, courage, confidence, honesty, and other positive _______ to empower its scouts.',['abilities','factors','phenomena','traits'],3,'Name the category of the examples before filling the blank.','Compassion, courage, confidence, and honesty are character traits. Factors are things that contribute to a result; abilities are skills; phenomena are observable events.',{chosen:1,seconds:2}),
    vr(34,'Context and cause','Doc Adams, a baseball player in the 1840s and 1850s, is credited with the invention of the shortstop position, an idea he _______ to field short throws from outfielders.',['conceived','duplicated','loathed','ridiculed'],0,'Underline “invention” and “idea.” Predict “thought of.”','Conceived means thought of or developed an idea. Loathed means hated, which does not express inventing the position. Duplicated means copied; ridiculed means mocked.',{chosen:2,seconds:6}),
    qr(16,'Translate a difference into an equation','Harry and Debra each own a landscaping company. Debra earns 4 times the amount that Harry earns for landscaping each week. After 7 weeks, Debra has earned $21,000 more than Harry. Which equation can be used to find H, the amount of money Harry earns per week landscaping?',['28H + 7H = 21,000','28H + 21,000 = 7H','21,000 − 7H = 28H','28H − 21,000 = 7H'],3,'Write “larger total − smaller total = difference” first.','Harry earns 7H in seven weeks; Debra earns 28H. Therefore 28H − 7H = 21,000. Rearranging gives 28H − 21,000 = 7H. Choice C incorrectly makes the difference equal to the sum of their earnings.',{chosen:2,seconds:67}),
    qr(18,'Best-fit line and unit rate','The graph shows time spent with a customer and the total amount the customer spent at a retail store. Using the line of best fit, what is the average amount of money earned per minute when 20 minutes are spent with a customer?',['$1.25','$1.55','$2.00','$3.10'],1,'Read the LINE at 20 minutes, then divide dollars by minutes—not a nearby dot.','The line gives about $30–$31 at 20 minutes. Dividing by 20 gives about $1.50–$1.55 per minute; $1.55 is the closest choice. The dot at (20, 25) would give $1.25, but the question asks for the line of best fit.',{chosen:0,seconds:65,diagram:'source-bestfit'}),
    qr(26,'Hourly rate versus total earnings','Sadie earns $70 working 7 hours. Leo earns $63 working 6 hours. Compare the quantities, assuming each person keeps the same hourly rate.',qc,0,'Find dollars per hour, then multiply by the NEW number of hours.','Sadie: 70 ÷ 7 = $10/hour, so 11 hours pays $110. Leo: 63 ÷ 6 = $10.50/hour, so 10 hours pays $105. A is greater even though Leo has the higher hourly rate.',{chosen:1,seconds:77,columns:['The amount Sadie earns working 11 hours','The amount Leo earns working 10 hours']}),
    qr(29,'Absolute value','Compare the quantities.',qc,2,'Absolute value is distance from zero. Reversing a subtraction changes its sign, not its distance.','Column A is |−90| = 90. Column B is |90| = 90. Thus |a − b| = |b − a| for any real numbers a and b.',{chosen:0,seconds:16,columns:['|10 − 100|','|100 − 10|']}),
    qr(32,'Two equations and substitution','Equation 1: m + 2n = 8. Equation 2: 2m + n = 10. Compare the quantities.',qc,2,'Use BOTH equations, then evaluate the exact expression in each column.','Double Equation 1: 2m + 4n = 16. Subtract Equation 2 to get 3n = 6, so n = 2. Then m = 4. Column B is n² = 4, so the quantities are equal. These two independent equations do determine m and n.',{chosen:3,seconds:49,columns:['m','n²']}),
    qr(34,'Area decomposition','Compare the areas inside the outlined figure on the coordinate grid.',qc,2,'Compare AREA, not the number of pieces. A large triangle may equal two small ones.','Each outer shaded triangle has area ½ × 4 × 4 = 8. The shaded left diamond consists of two triangles of area 4 each. Shaded area = 8 + 8 + 4 + 4 = 24. The central diamond has area ½ × 8 × 8 = 32; after subtracting its shaded 8, its unshaded area is 24.',{chosen:1,seconds:63,columns:['Area of the shaded region','Area of the unshaded region'],diagram:'shaded'}),
    qr(37,'Slope and similar triangles','Line AF is graphed on the coordinate plane with right triangles ABC and DEF. Compare the ratios of the segment lengths.',qc,2,'Same straight line → same steepness. Compare rise/run ratios, not triangle size.','The vertical and horizontal legs form right triangles along the same straight line, so AB/BC = DE/EF. The line slopes downward, so its signed slope is negative; these positive length ratios equal the magnitude of that slope.',{chosen:1,seconds:27,columns:['AB / BC','DE / EF'],diagram:'slope'})
  ];
  const a=[
    vr(8,'Precise verb meanings','In “The troops assaulted the fortress,” assaulted most nearly means:',['abandoned','attacked','repaired','guarded'],1,'Replace the word with a simple verb.','Assaulted means attacked, not defended or left behind.'),
    vr(9,'Multiple meanings','The instructions were obscure, so even experienced players could not follow them. Obscure most nearly means:',['popular','brief','unclear','repeated'],2,'Use “could not follow” as the clue.','Here obscure means hard to understand. Short instructions can still be clear; brief is not the same meaning.'),
    vr(10,'Opposite-word traps','Which word is closest in meaning to DIVULGE?',['hide','discover','deny','disclose'],3,'To divulge a secret is to let it become known.','Divulge and disclose both mean reveal. Discover means find out, not necessarily tell anyone.'),
    vr(11,'Word families and roles','The gifted orator held the audience’s attention throughout her speech. An orator is a:',['public speaker','careful listener','stage designer','bodyguard'],0,'Look at what the person is doing.','An orator delivers speeches. The sentence confirms this with “audience” and “speech.”'),
    vr(12,'Quantity and degree','After hours of work, his paltry payment barely bought a snack. Paltry means:',['generous','inadequate','guaranteed','delayed'],1,'Barely enough points to a small amount, not late payment.','Paltry means meager or insufficient. The sentence gives no evidence about when payment arrived.'),
    vr(17,'Multiple meanings','She spoke with conviction because she firmly believed in the plan. Conviction means:',['resentment','permission','certainty','secrecy'],2,'Ask which meaning fits “firmly believed.”','Conviction here is firm belief or certainty, not a legal verdict or anger.'),
    vr(18,'Useful word parts','The coach’s encouragement emboldened the nervous runner. It made the runner more:',['obedient','famous','eligible','confident'],3,'Find BOLD inside the word: bold means brave or confident.','Embolden means give confidence or courage. It does not mean grant eligibility or fame.'),
    vr(31,'Category clues','Patience, kindness, and honesty are admirable _______ in a teammate.',['traits','techniques','events','instruments'],0,'What category contains every example?','All three are personal qualities, or traits. Techniques are methods for doing something.'),
    vr(34,'Context and cause','The engineer _______ a new device after imagining a better way to clean the water.',['resented','conceived','copied','discarded'],1,'“New” and “imagining” point to creating an idea.','Conceived means thought of. Copied would mean reproducing something that already existed.'),
    qr(16,'Translate a difference into an equation','Mina earns 3 times Leo’s weekly pay. After 5 weeks Mina has earned $8,000 more than Leo. If L is Leo’s weekly pay, which equation represents this?',['15L + 5L = 8,000','8,000 − 5L = 15L','15L − 5L = 8,000','5L − 15L = 8,000'],2,'Larger five-week total minus smaller five-week total.','Mina’s five-week total is 15L and Leo’s is 5L. Their difference is 8,000; it is not their sum.'),
    qr(18,'Best-fit line and unit rate','At 15 minutes, the line of best fit in the graph predicts the total amount spent. What is the predicted average amount spent per minute?',['$1.20','$1.50','$30.00','$2.00'],3,'Use the line, then divide by time.','The line gives $30 at 15 minutes. $30 ÷ 15 = $2.00 per minute. The plotted dot at 15 minutes is not the line’s prediction.',{diagram:'bestfit-a'}),
    qr(26,'Hourly rate versus total earnings','Ava earns $54 in 6 hours. Ben earns $60 in 5 hours. Their hourly rates stay constant.',qc,2,'Compute each hourly rate and each new total.','Ava earns $9/hour: 8 × 9 = $72. Ben earns $12/hour: 6 × 12 = $72. The totals are equal.',{columns:['Ava’s earnings for 8 hours','Ben’s earnings for 6 hours']}),
    qr(29,'Absolute value','Compare the quantities.',qc,0,'Finish what is inside the bars before taking the distance from zero.','|7 − 25| = 18 and |25 − 9| = 16, so Column A is greater. Not every absolute-value comparison is equal.',{columns:['|7 − 25|','|25 − 9|']}),
    qr(32,'Two equations and substitution','m + 2n = 11 and 2m + n = 13. Compare the quantities.',qc,1,'Solve the system before squaring n.','Double the first equation and subtract the second: 3n = 9, so n = 3. Then m = 5. Compare 5 with 9: Column B is greater.',{columns:['m','n²']}),
    qr(34,'Area decomposition','A 10 by 6 rectangle contains a shaded triangle with base 10 and perpendicular height 4. Everything else in the rectangle is unshaded.',qc,1,'Find the whole area and subtract the shaded area.','The rectangle’s area is 60. The triangle’s area is ½ × 10 × 4 = 20. The unshaded area is 40, so Column B is greater.',{columns:['Shaded area','Unshaded area'],diagram:'area-a'}),
    qr(37,'Slope and similar triangles','Two right triangles lie along the same straight line, with horizontal and vertical legs. The first has vertical leg 6 and horizontal leg 4. The second has vertical leg 9 and horizontal leg x. Compare the quantities.',qc,2,'Equal steepness gives equal vertical/horizontal ratios.','6/4 = 9/x. Cross-multiplying gives 6x = 36, so x = 6.',{columns:['x','6']})
  ];
  const b=[
    vr(8,'Precise verb meanings','Which word most nearly means CONFRONT?',['face','postpone','forgive','obey'],0,'Think “confront a difficult problem.”','Confront means face or meet directly. Postpone means delay dealing with it.'),
    vr(9,'Multiple meanings','The historian studied an obscure poet whose work few readers recognized. Obscure means:',['angry','little-known','confident','popular'],1,'“Few readers recognized” selects a different sense of obscure.','Here obscure means not well known. A word can have more than one related meaning.'),
    vr(10,'Opposite-word traps','Although he knew the ending, Omar refused to disclose it. He refused to _______ it.',['imagine','change','reveal','conceal'],2,'Replace the target word, not the entire phrase “refused to disclose.”','Disclose means reveal. “Refused to disclose” means he would not reveal it; that does not make disclose itself mean conceal.'),
    vr(11,'Word families and roles','The audience applauded the oration at the end of the ceremony. Oration most nearly means:',['decoration','invitation','costume','speech'],3,'Orator is the speaker; oration is what the speaker delivers.','An oration is a formal speech. The audience applauds after hearing it.'),
    vr(12,'Quantity and degree','MEAGER most nearly means:',['scant','certain','gloomy','dependent'],0,'Connect meager with a paltry amount.','Scant means barely enough or small in amount. Gloomy describes mood, not quantity.'),
    vr(17,'Multiple meanings','The club’s creed emphasized fairness and service. Creed means:',['punishment','set of beliefs','secret meeting','strong dislike'],1,'A creed states what a group believes.','A creed is a set of beliefs or principles. It connects to conviction in its belief-related meaning.'),
    vr(18,'Useful word parts','The good news heartened the volunteers. Heartened most nearly means:',['appointed','authorized','encouraged','examined'],2,'Hearten and embolden both increase courage or confidence.','Heartened means encouraged. Authorized means given permission, which is different.'),
    vr(31,'Category clues','Unlike juggling and swimming, generosity is a character _______ rather than a learned physical skill.',['event','tool','factor','trait'],3,'Contrast personal quality with physical skill.','Generosity is a character trait. Juggling and swimming are abilities or skills.'),
    vr(34,'Context and cause','Before building a prototype, the inventor first _______ the idea for the machine.',['conceived','loathed','duplicated','ridiculed'],0,'An invention begins with thinking of an idea.','Conceived means formed in the mind. Loathed and ridiculed describe negative attitudes, not creating a design.'),
    qr(16,'Translate a difference into an equation','Nora earns 5 times Eli’s weekly pay. After 4 weeks Nora has earned $9,600 more than Eli. If E is Eli’s weekly pay, which equation is correct?',['20E + 4E = 9,600','20E − 9,600 = 4E','9,600 − 4E = 20E','4E − 9,600 = 20E'],1,'Larger total minus the difference equals smaller total.','The totals are 20E and 4E. Thus 20E − 4E = 9,600, equivalent to 20E − 9,600 = 4E.'),
    qr(18,'Best-fit line and unit rate','At 20 minutes, the line of best fit predicts the total amount spent. What is the predicted average amount spent per minute?',['$1.25','$2.00','$2.50','$50.00'],2,'Choose the line’s height, not the dot’s height.','The line predicts $50 at 20 minutes. $50 ÷ 20 = $2.50 per minute. $2.00 would come from the dot at (20, 40).',{diagram:'bestfit-b'}),
    qr(26,'Hourly rate versus total earnings','Kai earns $80 in 8 hours. Lia earns $66 in 6 hours. Their hourly rates stay constant.',qc,1,'A larger number of hours does not by itself guarantee more pay.','Kai earns $10/hour, so 12 hours pays $120. Lia earns $11/hour, so 11 hours pays $121. Column B is greater.',{columns:['Kai’s earnings for 12 hours','Lia’s earnings for 11 hours']}),
    qr(29,'Absolute value','Compare the quantities.',qc,2,'Reversed differences have the same absolute value.','|12 − 47| = |−35| = 35 and |47 − 12| = |35| = 35.',{columns:['|12 − 47|','|47 − 12|']}),
    qr(32,'Two equations and substitution','m + 2n = 11 and 2m + n = 16. Compare the quantities.',qc,0,'Use elimination, then compare m with n squared.','Double the first equation and subtract the second: 3n = 6, so n = 2. Then m = 7. Since n² = 4, Column A is greater.',{columns:['m','n²']}),
    qr(34,'Area decomposition','A 12 by 8 rectangle is divided by a diagonal from one corner to the opposite corner. One of the two resulting triangles is shaded.',qc,2,'A rectangle’s diagonal divides its area into two equal triangles.','The whole area is 12 × 8 = 96. Each triangle has area ½ × 12 × 8 = 48, so shaded and unshaded areas are equal.',{columns:['Shaded area','Unshaded area'],diagram:'area-b'}),
    qr(37,'Slope and similar triangles','Two right triangles lie along the same straight line, with horizontal and vertical legs. The first has vertical leg 4 and horizontal leg 6. The second has vertical leg 10 and horizontal leg x. Compare the quantities.',qc,0,'Keep vertical/horizontal in the same order for both triangles.','4/6 = 10/x. Thus 4x = 60 and x = 15. Compare 15 with 14: Column A is greater.',{columns:['x','14']})
  ];
  root.MARCO_ISEE_PRACTICE=[{id:'original',number:1,label:'Original wrong questions',questions:originals},{id:'similar-a',number:2,label:'Timed similar practice A',timeLimitSeconds:690,questions:a},{id:'similar-b',number:3,label:'Timed similar practice B',timeLimitSeconds:690,questions:b}];
})(window);
