(function(root){
  'use strict';
  const old=root.MARCO_ISEE_PRACTICE;
  root.MARCO_ISEE_LEGACY=[old[0]];
  const q=(section,n,skill,prompt,choices,correct,tip,explanation,extra={})=>({source:({VR:1000,QR:2000,MA:3000})[section]+n,section,number:n,skill,prompt,choices,correct,tip,explanation,...extra});
  const ma=(...args)=>q('MA',...args),vr=(...args)=>q('VR',...args),qr=(...args)=>q('QR',...args);
  const qc=old[0].questions.find(q=>q.number===26&&q.section==='QR').choices;
  const pts=[[-4,7],[-1,2],[3,1],[2,7]],rows=n=>Array.from({length:n},(_,i)=>i+1);
  const original=[
    ma(12,'Negative signs and order of operations','Which expression has a value of −22?',['5 × 2 + 12','−5 × 2 − 12','5 × 2 − (−12)','−5 × 2 − (−12)'],1,'Multiply first. Subtracting a negative means adding.','B is −10 − 12 = −22. A and C both equal 22; D equals 2. Keep the sign attached to each number.',{chosen:2,seconds:35}),
    ma(25,'Identify a transformation','Quadrilateral ABCD has been transformed to produce image A′B′C′D′. What type of transformation was performed?',['translation','reflection','rotation','flip'],0,'Track one vertex, then check that EVERY vertex moves the same way.','Each vertex moves 10 units down, with no turn or reversal. The figure keeps its size and orientation, so the transformation is a translation, not a reflection (flip).',{chosen:1,seconds:46,diagram:'ma-transform',points:pts,imagePoints:pts.map(([x,y])=>[x,y-10]),gridRange:10}),
    ma(26,'Smallest prime factor','What number is the smallest prime factor of 42?',['1','2','3','7'],1,'Start with the smallest prime, 2. Remember: 1 is NOT prime.','42 = 2 × 3 × 7. All three numbers are prime factors, but 2 is the smallest. A prime number has exactly two positive factors.',{chosen:2,seconds:40}),
    ma(29,'Growing shape patterns','The first four shapes in a pattern are shown. If the pattern continues, which choice shows the sixth shape?',['Six rows: 1, 2, 3, 4, 5, 6 squares','Five rows: 1, 1, 2, 3, 4 squares','Five rows: 1, 2, 3, 4, 6 squares','Five rows: 1, 2, 3, 4, 5 squares'],0,'Circle the requested position: SIXTH, not next. Add a new bottom row each time.','The first four shapes have 1, 3, 6, and 10 squares. The fifth adds 5 squares (15 total); the sixth adds 6 (21 total), with six rows. D is only the fifth shape.',{chosen:3,seconds:12,diagram:'ma-pattern',patternStages:[rows(1),rows(2),rows(3),rows(4)],choiceShapes:[rows(6),[1,1,2,3,4],[1,2,3,4,6],rows(5)]}),
    ma(37,'Remaining fraction at a constant rate','Mindy drinks 5/6 of a bottle of water in 2 minutes. At the same constant rate, how many seconds will it take her to drink the rest?',['20 seconds','24 seconds','140 seconds','144 seconds'],1,'Compare the remaining amount with the amount ALREADY consumed. Convert minutes to seconds.','The remaining 1/6 is one-fifth of the 5/6 already drunk. Two minutes = 120 seconds, so the rest takes 120 ÷ 5 = 24 seconds. Do not take one-sixth of the time: that time was for only 5/6 of the bottle.',{chosen:0,seconds:36}),
    ma(41,'Rearrange the kite area formula','Kite ABCD has area A = ½pq, where p and q are its diagonal lengths. If AC = 18 feet and the area is 108 square feet, what is the length of BD?',['3 feet','6 feet','12 feet','45 feet'],2,'Undo the one-half BEFORE dividing: other diagonal = 2 × area ÷ known diagonal.','108 = ½ × 18 × BD = 9 × BD. Therefore BD = 108 ÷ 9 = 12 feet. Dividing 108 by 18 gives 6, but forgets the one-half in the formula.',{chosen:1,seconds:62,diagram:'ma-kite',diagonal:18}),
    ma(42,'Square area minus circle area','A circle is inscribed in the shaded square on the grid. Each grid cell is 1 centimeter × 1 centimeter. In square centimeters, what is the area inside the square but outside the circle? (Circle area = πr².)',['32 − 8π','32 − 16π','64 − 8π','64 − 16π'],3,'Count grid INTERVALS for the square side. The circle’s diameter equals that side; radius is HALF.','The shaded square is 8 × 8, so its area is 64. The circle has diameter 8 and radius 4; its area is 16π. Subtract: 64 − 16π square centimeters.',{chosen:1,seconds:23,diagram:'ma-circle',side:8}),
    ma(44,'Independent events: both means multiply','Arianna randomly selects a whole number from 1 to 5 inclusive, then independently selects a whole number from 6 to 11 inclusive. What is the probability that both numbers are even?',['1/5','5/11','7/10','9/10'],0,'For independent choices, BOTH / AND means multiply the two probabilities.','There are 2 even numbers out of 5 in the first range, and 3 out of 6 in the second. Multiply: (2/5) × (3/6) = 6/30 = 1/5. Adding gives 7/10, but does not find the chance that both conditions happen.',{chosen:2,seconds:42}),
    ma(45,'Cylinder volume: diameter versus radius','A right cylinder has volume 9π cubic inches and diameter 3 inches. What is its height? (V = πr²h.)',['3 inches','4 inches','6 inches','9 inches'],1,'Halve the diameter, SQUARE the radius, then divide volume by πr².','The radius is 3/2 inches. Thus 9π = π × (3/2)² × h = (9π/4)h, so h = 4 inches. The given 3 is the diameter, not the height or radius.',{chosen:0,seconds:22,diagram:'ma-cylinder',diameter:3})
  ];
  // A third VR/QR counterpart: the previous two sets retain their IDs and answer keys.
  const c=[
    vr(8,'Precise verb meanings','The rival team launched an assault on the defenders’ goal. ASSAULT most nearly means:',['attack','agreement','delay','surrender'],0,'Use the action in the sentence, not the mood.','An assault is an attack. Here it describes an aggressive attempt to reach the goal, not an agreement or retreat.'),
    vr(9,'Multiple meanings','The speaker’s obscure explanation left the audience puzzled. OBSCURE most nearly means:',['famous','unclear','exciting','uncovered'],1,'Puzzled tells you which meaning fits.','Here obscure means difficult to understand. It can also mean little-known, but this sentence is about an explanation’s clarity.'),
    vr(10,'Opposite-word traps','The report will disclose the results tomorrow. DISCLOSE most nearly means:',['conceal','predict','reveal','change'],2,'Make known is the same as reveal, not hide.','Disclose means reveal or make known. Predict means forecast before knowing the results; conceal is the opposite.'),
    vr(11,'Word families and roles','Which person is most accurately described as an ORATOR?',['A person who guards a doorway','A person who paints scenery','A person who represents a country','A person who gives public speeches'],3,'Link orator to oral and oration.','An orator is a public speaker. Other people may sometimes speak, but speaking publicly is the defining role here.'),
    vr(12,'Quantity and degree','The paltry harvest was not enough to feed the village. PALTRY most nearly means:',['meager','abundant','rotten','delayed'],0,'Not enough is an amount clue.','Paltry means very small or inadequate; meager is the closest word. The sentence does not say the crops were spoiled or late.'),
    vr(17,'Multiple meanings','His conviction that everyone deserved fairness guided his decisions. CONVICTION most nearly means:',['anger','firm belief','secret','legal punishment'],1,'Ask whether the sentence describes a belief or a court case.','Conviction here means a firmly held belief. The fairness idea guiding his choices makes the belief meaning clear.'),
    vr(18,'Useful word parts','The teacher’s praise emboldened Maya to speak to the class. EMBOLDENED most nearly means:',['entitled','selected','encouraged','confused'],2,'Made bold means gave courage.','Emboldened means gave confidence or courage. Entitled means gave a right or permission; it does not necessarily make someone brave.'),
    vr(31,'Category clues','A leader’s honesty, courage, and patience are valuable character _______.',['tools','events','measurements','traits'],3,'Name the category shared by all three examples.','Honesty, courage, and patience are qualities of character, or traits. They are not events or instruments.'),
    vr(34,'Context and cause','The designer _______ a new bridge design before making the first drawing.',['conceived','duplicated','loathed','ridiculed'],0,'Creating a new idea comes before drawing it.','Conceived means thought of or formed in the mind. Duplicated means copied something already made; loathed and ridiculed express dislike.'),
    qr(16,'Translate a difference into an equation','Jade earns 4 times Owen’s weekly pay. After 6 weeks Jade has earned $7,200 more than Owen. If O is Owen’s weekly pay, which equation is correct?',['24O + 6O = 7,200','24O − 6O = 7,200','7,200 − 6O = 24O','6O − 24O = 7,200'],1,'Write the two six-week totals before taking their difference.','Jade earns 24O and Owen earns 6O. Larger total minus smaller total equals 7,200: 24O − 6O = 7,200.'),
    qr(18,'Best-fit line and unit rate','At 20 minutes, the line of best fit predicts the total amount spent. What is the predicted average amount spent per minute?',['$1.00','$1.50','$2.00','$30.00'],1,'Read the best-fit line, then divide dollars by minutes.','The line predicts $30 at 20 minutes. Dividing 30 by 20 gives $1.50 per minute. A dot can lie above or below the line.',{diagram:'bestfit-c'}),
    qr(26,'Hourly rate versus total earnings','Noah earns $72 in 8 hours. Emma earns $88 in 8 hours. Their hourly rates stay constant.',qc,0,'Multiply each hourly rate by the NEW hours.','Noah earns $9/hour and earns $108 in 12 hours. Emma earns $11/hour and earns $99 in 9 hours. Column A is greater.',{columns:['Noah’s earnings for 12 hours','Emma’s earnings for 9 hours']}),
    qr(29,'Absolute value','Compare the quantities.',qc,1,'Evaluate inside each pair of bars, then remove the sign.','|9 − 31| = 22 and |31 − 5| = 26. Column B is greater.',{columns:['|9 − 31|','|31 − 5|']}),
    qr(32,'Two equations and substitution','m + 2n = 14 and 2m + n = 16. Compare the quantities.',qc,1,'Solve both equations; square n only after finding n.','Double the first equation and subtract the second: 3n = 12, so n = 4 and m = 6. Compare 6 with 16: Column B is greater.',{columns:['m','n²']}),
    qr(34,'Area decomposition','A 9 by 8 rectangle contains a shaded triangle with base 9 and perpendicular height 6. Everything else is unshaded.',qc,1,'Triangle area is half base times height; subtract from the rectangle.','Whole area = 9 × 8 = 72. Shaded area = ½ × 9 × 6 = 27. Unshaded area = 72 − 27 = 45. Column B is greater.',{columns:['Shaded area','Unshaded area'],diagram:'area-c'}),
    qr(37,'Slope and similar triangles','Two right triangles lie along the same straight line, with horizontal and vertical legs. The first has vertical leg 8 and horizontal leg 6. The second has vertical leg 12 and horizontal leg x. Compare the quantities.',qc,0,'Use the same vertical/horizontal ratio for both triangles.','8/6 = 12/x, so 8x = 72 and x = 9. Column A is greater than 8.',{columns:['x','8']})
  ];

  const d=[
    vr(8,'Precise verb meanings','ASSAIL most nearly means:',['attack','approve','avoid','assemble'],0,'Think of assailing a fortress: launching an attack.','Assail means attack, either physically or with strong criticism. Approve means agree with, and avoid means stay away.'),
    vr(9,'Multiple meanings','The meaning of the faded inscription was obscure. OBSCURE most nearly means:',['obvious','unclear','ordinary','recent'],1,'Ask whether the meaning can be understood easily.','Obscure means unclear or difficult to understand here. A faded inscription can be hard to read and interpret.'),
    vr(10,'Opposite-word traps','REVEAL most nearly means:',['conceal','retain','disclose','replace'],2,'Revealing information makes it known.','Reveal and disclose both mean make known. Conceal means hide, which is the opposite; retain means keep.'),
    vr(11,'Word families and roles','The orator addressed a large crowd. ORATOR most nearly means:',['spectator','messenger','translator','speaker'],3,'An orator delivers an oration: a speech.','An orator is a public speaker. A spectator watches an event, while a translator changes words into another language.'),
    vr(12,'Quantity and degree','SCANT most nearly means:',['meager','plentiful','careful','costly'],0,'A scant supply is barely enough.','Scant means small or insufficient in amount, like meager or paltry. Plentiful means abundant and is the opposite.'),
    vr(17,'Multiple meanings','Despite criticism, she held to her conviction that the plan would work. CONVICTION means:',['fear','firm belief','courtroom','confusion'],1,'Look at the idea she continues to believe.','Conviction is a firmly held belief here. This sentence concerns confidence in a plan, rather than a criminal verdict.'),
    vr(18,'Useful word parts','The cheering crowd emboldened the shy performer. EMBOLDENED means:',['dismissed','permitted','encouraged','interrupted'],2,'Find bold: the crowd made the performer braver.','Emboldened means gave courage or confidence. Permission allows an action but does not necessarily make someone confident.'),
    vr(31,'Category clues','Integrity and perseverance are character _______ that employers often admire.',['instructions','possessions','occasions','traits'],3,'Both examples describe personal qualities.','Traits are qualities of a person’s character. Integrity and perseverance are qualities, rather than possessions or events.'),
    vr(34,'Context and cause','After noticing the problem, the scientist _______ a new way to solve it.',['conceived','resented','imitated','rejected'],0,'A new solution begins as an idea in the mind.','Conceived means thought of or formed an idea. Imitated means copied; rejected means refused to accept.'),
    qr(16,'Translate a difference into an equation','Tara earns 6 times Will’s weekly pay. After 3 weeks Tara has earned $4,500 more than Will. If W is Will’s weekly pay, which equation is correct?',['18W + 3W = 4,500','18W − 3W = 4,500','3W − 18W = 4,500','18W − 4,500 = −3W'],1,'Write both three-week totals, then subtract smaller from larger.','Tara earns 18W in three weeks and Will earns 3W. Their difference is 4,500, so 18W − 3W = 4,500.'),
    qr(18,'Best-fit line and unit rate','A line of best fit predicts that a customer spends $42 in 28 minutes. What average spending per minute does that prediction imply?',['$1.25','$1.50','$2.00','$42.00'],1,'Divide the predicted dollars by the number of minutes.','The predicted rate is 42 ÷ 28 = $1.50 per minute. The total amount spent is not the amount spent each minute.'),
    qr(26,'Hourly rate versus total earnings','Alex earns $84 in 7 hours. Bea earns $90 in 6 hours. Their hourly rates stay constant.',qc,2,'Calculate each hourly rate before multiplying by the new hours.','Alex earns $12 per hour, so 10 hours pays $120. Bea earns $15 per hour, so 8 hours also pays $120. The quantities are equal.',{columns:['Alex’s earnings for 10 hours','Bea’s earnings for 8 hours']}),
    qr(29,'Absolute value','Compare the quantities.',qc,0,'Calculate each difference inside the bars, then take its magnitude.','|14 − 39| = 25, while |39 − 17| = 22. Column A is greater. Absolute values need not be equal when the subtractions use different numbers.',{columns:['|14 − 39|','|39 − 17|']}),
    qr(32,'Two equations and substitution','m + 2n = 17 and 2m + n = 19. Compare the quantities.',qc,1,'Use both equations and square n only after solving.','Double the first equation and subtract the second: 3n = 15, so n = 5 and m = 7. Compare 7 with 25: Column B is greater.',{columns:['m','n²']}),
    qr(34,'Area decomposition','A 14 by 6 rectangle contains a shaded triangle with base 14 and perpendicular height 5. Everything else is unshaded.',qc,1,'Find triangle area, then subtract it from the rectangle area.','Rectangle area = 14 × 6 = 84. Shaded area = ½ × 14 × 5 = 35. Unshaded area = 84 − 35 = 49, so Column B is greater.',{columns:['Shaded area','Unshaded area']}),
    qr(37,'Slope and similar triangles','Two right triangles lie along the same straight line, with horizontal and vertical legs. The first has vertical leg 5 and horizontal leg 4. The second has vertical leg 15 and horizontal leg x. Compare the quantities.',qc,2,'The vertical-to-horizontal ratio is the same for both triangles.','5/4 = 15/x, so 5x = 60 and x = 12. Both columns equal 12.',{columns:['x','12']})
  ];

  function variants(k){
    const cfg=[
      {a:4,b:9,neg:2,prime:75,factor:3,primeChoices:['1','5','3','15'],primeC:2,stage:5,patternChoices:['10','15','20','21'],patternC:1,part:3,whole:4,minutes:3,seconds:60,rateChoices:['60','45','90','240'],rateC:0,p:16,area:80,diag:10,kiteChoices:['5','10','20','80'],kiteC:1,side:10,circleChoices:['100 − 10π','50 − 25π','100 − 25π','100 − 100π'],circleC:2,ranges:[[1,6],[7,11]],probChoices:['9/10','1/2','2/5','1/5'],probC:3,diam:4,vol:48,h:12,cylChoices:['3','6','8','12'],cylC:3},
      {a:6,b:7,neg:0,prime:77,factor:7,primeChoices:['7','1','11','77'],primeC:0,stage:7,patternChoices:['28','21','35','36'],patternC:0,part:4,whole:5,minutes:2,seconds:30,rateChoices:['24','120','30','150'],rateC:2,p:20,area:140,diag:14,kiteChoices:['7','10','28','14'],kiteC:3,side:6,circleChoices:['36 − 9π','18 − 9π','36 − 6π','36 − 36π'],circleC:0,ranges:[[1,8],[9,14]],probChoices:['1','1/4','1/2','3/8'],probC:1,diam:6,vol:45,h:5,cylChoices:['1.25','5','9','15'],cylC:1},
      {a:3,b:8,neg:3,prime:91,factor:7,primeChoices:['13','7','1','91'],primeC:1,stage:8,patternChoices:['28','32','45','36'],patternC:3,part:7,whole:8,minutes:7,seconds:60,rateChoices:['52.5','60','360','480'],rateC:1,p:12,area:54,diag:9,kiteChoices:['9','4.5','18','6'],kiteC:0,side:12,circleChoices:['144 − 12π','144 − 36π','72 − 36π','144 − 144π'],circleC:1,ranges:[[2,7],[8,12]],probChoices:['11/10','3/5','3/10','1/2'],probC:2,diam:5,vol:50,h:8,cylChoices:['8','2','10','25'],cylC:0}
,
      {a:5,b:6,neg:1,prime:55,factor:5,primeChoices:['1','11','5','55'],primeC:2,stage:9,patternChoices:['36','45','54','55'],patternC:1,part:5,whole:6,minutes:4,seconds:48,rateChoices:['40','48','60','288'],rateC:1,p:14,area:84,diag:12,kiteChoices:['6','12','24','84'],kiteC:1,side:14,circleChoices:['196 − 14π','98 − 49π','196 − 49π','196 − 196π'],circleC:2,ranges:[[1,10],[11,16]],probChoices:['1','1/4','1/2','3/10'],probC:1,diam:8,vol:112,h:7,cylChoices:['1.75','7','14','28'],cylC:1}
    ][k];
    const expressions=[`${cfg.a} × ${cfg.a} + ${cfg.b}`,`−${cfg.a} × ${cfg.a} − (−${cfg.b})`,`${cfg.a} × ${cfg.a} − ${cfg.b}`];
    expressions.splice(cfg.neg,0,`−${cfg.a} × ${cfg.a} − ${cfg.b}`);
    const base=[[-4,4],[-3,1],[-1,2],[-1,4]],moved=base.map(([x,y])=>k===0||k===3?[x+3,y+1]:k===1?[-x,y]:[-x,-y]);
    const transformC=[1,0,3,1][k],transformWhy=['Every point moves 3 units right and 1 unit up. The figure does not turn or flip.','Each x-coordinate changes sign while each y-coordinate stays the same: a reflection across the y-axis.','Both coordinates change sign: a 180° rotation about the origin. A translation would preserve the directions of corresponding edges.'][k===3?0:k];
    const [r1,r2]=cfg.ranges,even=([lo,hi])=>Array.from({length:hi-lo+1},(_,i)=>lo+i).filter(n=>n%2===0).length;
    return [
      ma(12,'Negative signs and order of operations',`Which expression equals −${cfg.a*cfg.a+cfg.b}?`,expressions,cfg.neg,'Multiply first; subtracting a positive makes a negative more negative.',`−${cfg.a} × ${cfg.a} − ${cfg.b} = −${cfg.a*cfg.a} − ${cfg.b} = −${cfg.a*cfg.a+cfg.b}. Subtracting a negative would add instead.`,{check:{type:'negative',a:cfg.a,b:cfg.b}}),
      ma(25,'Identify a transformation','The graph shows ABCD and its image A′B′C′D′. Which single transformation produces the image?',['reflection','translation','dilation','rotation'],transformC,'Check how the vertices move, not just where the figure ends up.',transformWhy,{diagram:'ma-transform',points:base,imagePoints:moved,gridRange:6,check:{type:'transform',kind:k===3?0:k}}),
      ma(26,'Smallest prime factor',`What is the smallest prime factor of ${cfg.prime}?`,cfg.primeChoices,cfg.primeC,'Try primes in increasing order: 2, 3, 5, 7… A factor must divide exactly.',`${cfg.prime} = ${cfg.factor} × ${cfg.prime/cfg.factor}. No smaller prime divides ${cfg.prime}, so ${cfg.factor} is the smallest prime factor. One is not prime.`,{check:{type:'prime',value:cfg.prime}}),
      ma(29,'Growing shape patterns',`The first four shapes are shown. Each new shape adds a bottom row with one more square. How many small squares are in shape ${cfg.stage}?`,cfg.patternChoices,cfg.patternC,'Write the shape numbers. Add every row up to the requested shape.',`Shape ${cfg.stage} has ${rows(cfg.stage).join(' + ')} = ${cfg.stage*(cfg.stage+1)/2} squares. Do not stop at the fifth shape just because four shapes are shown.`,{diagram:'ma-pattern',patternStages:[rows(1),rows(2),rows(3),rows(4)],check:{type:'pattern',stage:cfg.stage}}),
      ma(37,'Remaining fraction at a constant rate',`A student drinks ${cfg.part}/${cfg.whole} of a bottle in ${cfg.minutes} minutes. At the same constant rate, how many seconds are needed to drink the rest?`,cfg.rateChoices.map(n=>n+' seconds'),cfg.rateC,'The remaining 1 part takes one over the number of parts already drunk, times the elapsed time.',`The remaining 1/${cfg.whole} is 1/${cfg.part} of the ${cfg.part}/${cfg.whole} already consumed. ${cfg.minutes} minutes = ${cfg.minutes*60} seconds. Divide by ${cfg.part}: ${cfg.seconds} seconds.`,{check:{type:'rate',part:cfg.part,whole:cfg.whole,minutes:cfg.minutes}}),
      ma(41,'Rearrange the kite area formula',`A kite has area ${cfg.area} square feet and diagonal AC = ${cfg.p} feet. Its area is ½ × AC × BD. What is BD?`,cfg.kiteChoices.map(n=>n+' feet'),cfg.kiteC,'Other diagonal = twice the area divided by the known diagonal.',`BD = 2 × ${cfg.area} ÷ ${cfg.p} = ${cfg.diag} feet. Check: ½ × ${cfg.p} × ${cfg.diag} = ${cfg.area}.`,{diagram:'ma-kite',diagonal:cfg.p,check:{type:'kite',area:cfg.area,p:cfg.p}}),
      ma(42,'Square area minus circle area',`A circle fits exactly inside a square with side length ${cfg.side} cm. The region inside the square but outside the circle is shaded. What is its area in square centimeters? (Circle area = πr².)`,cfg.circleChoices,cfg.circleC,'Use side² for the square and (side ÷ 2)² for the circle.',`Square area = ${cfg.side}² = ${cfg.side**2}. Circle radius = ${cfg.side/2}, so circle area = ${(cfg.side/2)**2}π. Shaded area = ${cfg.side**2} − ${(cfg.side/2)**2}π.`,{diagram:'ma-circle',side:cfg.side,check:{type:'circle',side:cfg.side}}),
      ma(44,'Independent events: both means multiply',`A number is randomly chosen from ${r1[0]} to ${r1[1]} inclusive, then a number is independently chosen from ${r2[0]} to ${r2[1]} inclusive. What is the probability that BOTH are even?`,cfg.probChoices,cfg.probC,'Count the endpoints too. Multiply for two independent events both happening.',`The first chance is ${even(r1)}/${r1[1]-r1[0]+1}; the second is ${even(r2)}/${r2[1]-r2[0]+1}. Multiply and simplify to ${cfg.probChoices[cfg.probC]}. Adding the probabilities does not give the chance that both numbers are even.`,{check:{type:'probability',ranges:cfg.ranges}}),
      ma(45,'Cylinder volume: diameter versus radius',`A right cylinder has volume ${cfg.vol}π cubic inches and diameter ${cfg.diam} inches. What is its height? (V = πr²h.)`,cfg.cylChoices.map(n=>n+' inches'),cfg.cylC,'Radius is half the diameter. Square it before dividing.',`Radius = ${cfg.diam/2} inches. h = ${cfg.vol}π ÷ [π × (${cfg.diam/2})²] = ${cfg.vol} ÷ ${(cfg.diam/2)**2} = ${cfg.h} inches.`,{diagram:'ma-cylinder',diameter:cfg.diam,check:{type:'cylinder',volume:cfg.vol,diameter:cfg.diam}})
    ];
  }
  root.MARCO_ISEE_LEGACY.push({id:'similar-b',label:'Earlier Session 3 timed runs',timeLimitSeconds:1230,questions:[...old[2].questions,...variants(2)]});
  root.MARCO_ISEE_REVIEW=[...old[0].questions,...original];
  root.MARCO_ISEE_LEGACY_SOURCES=old[0].questions.map(q=>q.source);
  root.MARCO_ISEE_PRACTICE=[
    {id:'similar-c',number:1,label:'Similar practice 1',questions:[...c,...variants(0)]},
    {id:'similar-a',number:2,label:'Similar practice 2',questions:[...old[1].questions,...variants(1)]},
    {id:'similar-b-untimed',number:3,label:'Similar practice 3',questions:[...old[2].questions,...variants(2)]},
    {id:'similar-d',number:4,label:'Timed similar challenge 4',timeLimitSeconds:1230,questions:[...d,...variants(3)]}
  ];
})(window);
